// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AnalyticsControllerGetAgingReportData,
  AnalyticsControllerGetAgingReportResponses,
  AnalyticsControllerGetDashboardData,
  AnalyticsControllerGetDashboardResponses,
  AnalyticsControllerGetLhdnReportData,
  AnalyticsControllerGetLhdnReportResponses,
  AnalyticsControllerGetMonthlyRevenueData,
  AnalyticsControllerGetMonthlyRevenueResponses,
  ApprovalsControllerGetByInvoiceData,
  ApprovalsControllerGetByInvoiceResponses,
  ApprovalsControllerGetPendingData,
  ApprovalsControllerGetPendingResponses,
  ApprovalsControllerRequestApprovalData,
  ApprovalsControllerRequestApprovalResponses,
  ApprovalsControllerReviewApprovalData,
  ApprovalsControllerReviewApprovalResponses,
  AuthControllerForgotPasswordData,
  AuthControllerForgotPasswordResponses,
  AuthControllerGetSessionsData,
  AuthControllerGetSessionsErrors,
  AuthControllerGetSessionsResponses,
  AuthControllerLoginData,
  AuthControllerLoginErrors,
  AuthControllerLoginResponses,
  AuthControllerLogoutAllData,
  AuthControllerLogoutAllErrors,
  AuthControllerLogoutAllResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutErrors,
  AuthControllerLogoutResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshErrors,
  AuthControllerRefreshResponses,
  AuthControllerResetPasswordData,
  AuthControllerResetPasswordResponses,
  AuthControllerRevokeSessionData,
  AuthControllerRevokeSessionErrors,
  AuthControllerRevokeSessionResponses,
  AuthControllerSwitchCompanyData,
  AuthControllerSwitchCompanyResponses,
  CompaniesControllerCreateData,
  CompaniesControllerCreateErrors,
  CompaniesControllerCreateResponses,
  CompaniesControllerFindOneData,
  CompaniesControllerFindOneErrors,
  CompaniesControllerFindOneResponses,
  CompaniesControllerGetCurrentCompanyStatsData,
  CompaniesControllerGetCurrentCompanyStatsErrors,
  CompaniesControllerGetCurrentCompanyStatsResponses,
  CompaniesControllerGetMyCompaniesData,
  CompaniesControllerGetMyCompaniesErrors,
  CompaniesControllerGetMyCompaniesResponses,
  CompaniesControllerUpdateData,
  CompaniesControllerUpdateErrors,
  CompaniesControllerUpdateResponses,
  CreditMemosControllerCreateData,
  CreditMemosControllerCreateResponses,
  CreditMemosControllerFindByInvoiceData,
  CreditMemosControllerFindByInvoiceResponses,
  CreditMemosControllerIssueData,
  CreditMemosControllerIssueResponses,
  CreditMemosControllerVoidData,
  CreditMemosControllerVoidResponses,
  CustomersControllerBulkUploadData,
  CustomersControllerBulkUploadErrors,
  CustomersControllerBulkUploadResponses,
  CustomersControllerCreateData,
  CustomersControllerCreateErrors,
  CustomersControllerCreateResponses,
  CustomersControllerDeleteData,
  CustomersControllerDeleteErrors,
  CustomersControllerDeleteResponses,
  CustomersControllerDownloadErrorsData,
  CustomersControllerDownloadErrorsErrors,
  CustomersControllerDownloadErrorsResponses,
  CustomersControllerFindAllData,
  CustomersControllerFindAllErrors,
  CustomersControllerFindAllResponses,
  CustomersControllerFindOneData,
  CustomersControllerFindOneErrors,
  CustomersControllerFindOneResponses,
  CustomersControllerGetUploadStatusData,
  CustomersControllerGetUploadStatusErrors,
  CustomersControllerGetUploadStatusResponses,
  CustomersControllerRestoreData,
  CustomersControllerRestoreErrors,
  CustomersControllerRestoreResponses,
  CustomersControllerTrackProgressData,
  CustomersControllerTrackProgressErrors,
  CustomersControllerTrackProgressResponses,
  CustomersControllerUpdateData,
  CustomersControllerUpdateErrors,
  CustomersControllerUpdateResponses,
  EInvoiceSubmissionsControllerGetQrCodeData,
  EInvoiceSubmissionsControllerGetQrCodeResponses,
  EInvoiceSubmissionsControllerGetStatusData,
  EInvoiceSubmissionsControllerGetStatusResponses,
  EInvoiceSubmissionsControllerListSubmissionsData,
  EInvoiceSubmissionsControllerListSubmissionsResponses,
  EInvoiceSubmissionsControllerRetryData,
  EInvoiceSubmissionsControllerRetryResponses,
  HealthControllerCheckData,
  HealthControllerCheckErrors,
  HealthControllerCheckResponses,
  InvitesControllerAcceptInviteData,
  InvitesControllerAcceptInviteResponses,
  InvitesControllerPreviewInviteData,
  InvitesControllerPreviewInviteResponses,
  InvoicesControllerBulkFinalizeData,
  InvoicesControllerBulkFinalizeErrors,
  InvoicesControllerBulkFinalizeResponses,
  InvoicesControllerBulkSendData,
  InvoicesControllerBulkSendErrors,
  InvoicesControllerBulkSendResponses,
  InvoicesControllerCancelLhdnData,
  InvoicesControllerCancelLhdnErrors,
  InvoicesControllerCancelLhdnResponses,
  InvoicesControllerCloneInvoiceData,
  InvoicesControllerCloneInvoiceErrors,
  InvoicesControllerCloneInvoiceResponses,
  InvoicesControllerCreateData,
  InvoicesControllerCreateErrors,
  InvoicesControllerCreateResponses,
  InvoicesControllerDownloadDemoPdfData,
  InvoicesControllerDownloadDemoPdfErrors,
  InvoicesControllerDownloadDemoPdfResponses,
  InvoicesControllerExportInvoicesData,
  InvoicesControllerExportInvoicesErrors,
  InvoicesControllerExportInvoicesResponses,
  InvoicesControllerFinalizeData,
  InvoicesControllerFinalizeErrors,
  InvoicesControllerFinalizeResponses,
  InvoicesControllerFindAllData,
  InvoicesControllerFindAllErrors,
  InvoicesControllerFindAllResponses,
  InvoicesControllerFindOneData,
  InvoicesControllerFindOneErrors,
  InvoicesControllerFindOneResponses,
  InvoicesControllerGetAllowedTransitionsData,
  InvoicesControllerGetAllowedTransitionsErrors,
  InvoicesControllerGetAllowedTransitionsResponses,
  InvoicesControllerGetAuditTrailData,
  InvoicesControllerGetAuditTrailErrors,
  InvoicesControllerGetAuditTrailResponses,
  InvoicesControllerRemoveData,
  InvoicesControllerRemoveErrors,
  InvoicesControllerRemoveResponses,
  InvoicesControllerResendEmailData,
  InvoicesControllerResendEmailErrors,
  InvoicesControllerResendEmailResponses,
  InvoicesControllerSendData,
  InvoicesControllerSendErrors,
  InvoicesControllerSendResponses,
  InvoicesControllerSubmitEinvoiceData,
  InvoicesControllerSubmitEinvoiceErrors,
  InvoicesControllerSubmitEinvoiceResponses,
  InvoicesControllerUpdateData,
  InvoicesControllerUpdateErrors,
  InvoicesControllerUpdateResponses,
  InvoicesControllerVoidData,
  InvoicesControllerVoidErrors,
  InvoicesControllerVoidResponses,
  InvoiceTemplatesControllerCreateData,
  InvoiceTemplatesControllerCreateResponses,
  InvoiceTemplatesControllerFindAllData,
  InvoiceTemplatesControllerFindAllResponses,
  InvoiceTemplatesControllerFindOneData,
  InvoiceTemplatesControllerFindOneResponses,
  InvoiceTemplatesControllerRemoveData,
  InvoiceTemplatesControllerRemoveResponses,
  InvoiceTemplatesControllerSetDefaultData,
  InvoiceTemplatesControllerSetDefaultResponses,
  InvoiceTemplatesControllerUpdateData,
  InvoiceTemplatesControllerUpdateResponses,
  LhdnCredentialsControllerCreateCredentialsData,
  LhdnCredentialsControllerCreateCredentialsResponses,
  LhdnCredentialsControllerDeactivateCredentialsData,
  LhdnCredentialsControllerDeactivateCredentialsResponses,
  LhdnCredentialsControllerGetAuditLogData,
  LhdnCredentialsControllerGetAuditLogResponses,
  LhdnCredentialsControllerGetCredentialStatusData,
  LhdnCredentialsControllerGetCredentialStatusResponses,
  LhdnCredentialsControllerUpdateCredentialsData,
  LhdnCredentialsControllerUpdateCredentialsResponses,
  LhdnCredentialsControllerValidateCredentialsData,
  LhdnCredentialsControllerValidateCredentialsResponses,
  LhdnManagementControllerGetDocumentTypesData,
  LhdnManagementControllerGetDocumentTypesResponses,
  LhdnManagementControllerListNotificationsData,
  LhdnManagementControllerListNotificationsResponses,
  LhdnManagementControllerSyncNotificationsData,
  LhdnManagementControllerSyncNotificationsResponses,
  LhdnWebhookControllerHandleWebhookData,
  LhdnWebhookControllerHandleWebhookResponses,
  LhdnWebhookControllerHealthCheckData,
  LhdnWebhookControllerHealthCheckResponses,
  MembershipsControllerGetMembersData,
  MembershipsControllerGetMembersResponses,
  MembershipsControllerGetMyMembershipData,
  MembershipsControllerGetMyMembershipResponses,
  MembershipsControllerRemoveMemberData,
  MembershipsControllerRemoveMemberResponses,
  MembershipsControllerUpdateMembershipData,
  MembershipsControllerUpdateMembershipResponses,
  PaymentsControllerDeletePaymentData,
  PaymentsControllerDeletePaymentResponses,
  PaymentsControllerGetBalanceData,
  PaymentsControllerGetBalanceResponses,
  PaymentsControllerGetPaymentsData,
  PaymentsControllerGetPaymentsResponses,
  PaymentsControllerRecordPaymentData,
  PaymentsControllerRecordPaymentResponses,
  PlatformAuditControllerFindAllData,
  PlatformAuditControllerFindAllResponses,
  ProductsControllerCreateData,
  ProductsControllerCreateErrors,
  ProductsControllerCreateResponses,
  ProductsControllerDeleteData,
  ProductsControllerDeleteErrors,
  ProductsControllerDeleteResponses,
  ProductsControllerFindAllData,
  ProductsControllerFindAllErrors,
  ProductsControllerFindAllResponses,
  ProductsControllerFindOneData,
  ProductsControllerFindOneErrors,
  ProductsControllerFindOneResponses,
  ProductsControllerGetClassificationCodesData,
  ProductsControllerGetClassificationCodesErrors,
  ProductsControllerGetClassificationCodesResponses,
  ProductsControllerRestoreData,
  ProductsControllerRestoreErrors,
  ProductsControllerRestoreResponses,
  ProductsControllerUpdateData,
  ProductsControllerUpdateErrors,
  ProductsControllerUpdateResponses,
  QuotationsControllerAcceptData,
  QuotationsControllerAcceptErrors,
  QuotationsControllerAcceptResponses,
  QuotationsControllerConvertToInvoiceData,
  QuotationsControllerConvertToInvoiceErrors,
  QuotationsControllerConvertToInvoiceResponses,
  QuotationsControllerCreateData,
  QuotationsControllerCreateErrors,
  QuotationsControllerCreateResponses,
  QuotationsControllerFindAllData,
  QuotationsControllerFindAllErrors,
  QuotationsControllerFindAllResponses,
  QuotationsControllerFindOneData,
  QuotationsControllerFindOneErrors,
  QuotationsControllerFindOneResponses,
  QuotationsControllerRejectData,
  QuotationsControllerRejectErrors,
  QuotationsControllerRejectResponses,
  QuotationsControllerRemoveData,
  QuotationsControllerRemoveErrors,
  QuotationsControllerRemoveResponses,
  QuotationsControllerReviseData,
  QuotationsControllerReviseErrors,
  QuotationsControllerReviseResponses,
  QuotationsControllerSendData,
  QuotationsControllerSendErrors,
  QuotationsControllerSendResponses,
  QuotationsControllerUpdateData,
  QuotationsControllerUpdateErrors,
  QuotationsControllerUpdateResponses,
  RecurringInvoicesControllerCancelData,
  RecurringInvoicesControllerCancelErrors,
  RecurringInvoicesControllerCancelResponses,
  RecurringInvoicesControllerCreateData,
  RecurringInvoicesControllerCreateErrors,
  RecurringInvoicesControllerCreateResponses,
  RecurringInvoicesControllerFindAllData,
  RecurringInvoicesControllerFindAllErrors,
  RecurringInvoicesControllerFindAllResponses,
  RecurringInvoicesControllerFindOneData,
  RecurringInvoicesControllerFindOneErrors,
  RecurringInvoicesControllerFindOneResponses,
  RecurringInvoicesControllerPauseData,
  RecurringInvoicesControllerPauseErrors,
  RecurringInvoicesControllerPauseResponses,
  RecurringInvoicesControllerRemoveData,
  RecurringInvoicesControllerRemoveErrors,
  RecurringInvoicesControllerRemoveResponses,
  RecurringInvoicesControllerResumeData,
  RecurringInvoicesControllerResumeErrors,
  RecurringInvoicesControllerResumeResponses,
  SuperAdminAnalyticsControllerGetPlatformOverviewData,
  SuperAdminAnalyticsControllerGetPlatformOverviewResponses,
  SuperAdminAnalyticsControllerGetPlatformRevenueData,
  SuperAdminAnalyticsControllerGetPlatformRevenueResponses,
  SuperAdminAnalyticsControllerGetTopCompaniesData,
  SuperAdminAnalyticsControllerGetTopCompaniesResponses,
  SuperadminAuditControllerFindAllInvoiceAuditsData,
  SuperadminAuditControllerFindAllInvoiceAuditsResponses,
  SuperadminAuditControllerFindAllPlatformLogsData,
  SuperadminAuditControllerFindAllPlatformLogsResponses,
  SuperadminAuditControllerFindInvoiceAuditByUuidData,
  SuperadminAuditControllerFindInvoiceAuditByUuidResponses,
  SuperadminAuditControllerFindPlatformLogByIdData,
  SuperadminAuditControllerFindPlatformLogByIdResponses,
  SuperadminAuditControllerGetCompanyTimelineData,
  SuperadminAuditControllerGetCompanyTimelineResponses,
  SuperAdminCompaniesControllerDeleteData,
  SuperAdminCompaniesControllerDeleteErrors,
  SuperAdminCompaniesControllerDeleteResponses,
  SuperAdminCompaniesControllerFindAllData,
  SuperAdminCompaniesControllerFindAllErrors,
  SuperAdminCompaniesControllerFindAllResponses,
  SuperAdminCompaniesControllerRestoreData,
  SuperAdminCompaniesControllerRestoreErrors,
  SuperAdminCompaniesControllerRestoreResponses,
  SuperAdminCompaniesControllerToggleStatusData,
  SuperAdminCompaniesControllerToggleStatusErrors,
  SuperAdminCompaniesControllerToggleStatusResponses,
  SuperadminProductsControllerDeleteData,
  SuperadminProductsControllerDeleteErrors,
  SuperadminProductsControllerDeleteResponses,
  SuperadminProductsControllerFindAllData,
  SuperadminProductsControllerFindAllErrors,
  SuperadminProductsControllerFindAllResponses,
  SuperadminProductsControllerFindOneData,
  SuperadminProductsControllerFindOneErrors,
  SuperadminProductsControllerFindOneResponses,
  SuperadminProductsControllerRestoreData,
  SuperadminProductsControllerRestoreErrors,
  SuperadminProductsControllerRestoreResponses,
  SuperadminUsersControllerDeleteData,
  SuperadminUsersControllerDeleteErrors,
  SuperadminUsersControllerDeleteResponses,
  SuperadminUsersControllerFindAllData,
  SuperadminUsersControllerFindAllErrors,
  SuperadminUsersControllerFindAllResponses,
  SuperadminUsersControllerFindOneData,
  SuperadminUsersControllerFindOneErrors,
  SuperadminUsersControllerFindOneResponses,
  SuperadminUsersControllerInviteAdminData,
  SuperadminUsersControllerInviteAdminResponses,
  SuperadminUsersControllerRestoreData,
  SuperadminUsersControllerRestoreErrors,
  SuperadminUsersControllerRestoreResponses,
  TaxCategoriesControllerCreateData,
  TaxCategoriesControllerCreateErrors,
  TaxCategoriesControllerCreateResponses,
  TaxCategoriesControllerFindAllData,
  TaxCategoriesControllerFindAllResponses,
  TaxCategoriesControllerFindOneData,
  TaxCategoriesControllerFindOneErrors,
  TaxCategoriesControllerFindOneResponses,
  TaxCategoriesControllerRemoveData,
  TaxCategoriesControllerRemoveErrors,
  TaxCategoriesControllerRemoveResponses,
  TaxCategoriesControllerUpdateData,
  TaxCategoriesControllerUpdateErrors,
  TaxCategoriesControllerUpdateResponses,
  TaxCategoriesSuperAdminControllerCreateData,
  TaxCategoriesSuperAdminControllerCreateErrors,
  TaxCategoriesSuperAdminControllerCreateResponses,
  TaxCategoriesSuperAdminControllerFindAllData,
  TaxCategoriesSuperAdminControllerFindAllResponses,
  TaxCategoriesSuperAdminControllerFindOneData,
  TaxCategoriesSuperAdminControllerFindOneErrors,
  TaxCategoriesSuperAdminControllerFindOneResponses,
  TaxCategoriesSuperAdminControllerRemoveData,
  TaxCategoriesSuperAdminControllerRemoveResponses,
  TaxCategoriesSuperAdminControllerUpdateData,
  TaxCategoriesSuperAdminControllerUpdateResponses,
  TaxRulesControllerCreateData,
  TaxRulesControllerCreateErrors,
  TaxRulesControllerCreateResponses,
  TaxRulesControllerFindAllData,
  TaxRulesControllerFindAllResponses,
  TaxRulesControllerFindOneData,
  TaxRulesControllerFindOneErrors,
  TaxRulesControllerFindOneResponses,
  TaxRulesControllerRemoveData,
  TaxRulesControllerRemoveErrors,
  TaxRulesControllerRemoveResponses,
  TaxRulesControllerUpdateData,
  TaxRulesControllerUpdateErrors,
  TaxRulesControllerUpdateResponses,
  TaxRulesSuperAdminControllerCreateData,
  TaxRulesSuperAdminControllerCreateErrors,
  TaxRulesSuperAdminControllerCreateResponses,
  TaxRulesSuperAdminControllerFindAllData,
  TaxRulesSuperAdminControllerFindAllResponses,
  TaxRulesSuperAdminControllerFindOneData,
  TaxRulesSuperAdminControllerFindOneErrors,
  TaxRulesSuperAdminControllerFindOneResponses,
  TaxRulesSuperAdminControllerRemoveData,
  TaxRulesSuperAdminControllerRemoveResponses,
  TaxRulesSuperAdminControllerUpdateData,
  TaxRulesSuperAdminControllerUpdateResponses,
  UsersControllerCreateAdminData,
  UsersControllerCreateAdminErrors,
  UsersControllerCreateAdminResponses,
  UsersControllerCreateStaffData,
  UsersControllerCreateStaffErrors,
  UsersControllerCreateStaffResponses,
  UsersControllerFindCompanyStaffData,
  UsersControllerFindCompanyStaffErrors,
  UsersControllerFindCompanyStaffResponses,
  UsersControllerFindOneByCompanyData,
  UsersControllerFindOneByCompanyErrors,
  UsersControllerFindOneByCompanyResponses,
  UsersControllerInviteStaffData,
  UsersControllerInviteStaffErrors,
  UsersControllerInviteStaffResponses,
  UsersControllerUpdateData,
  UsersControllerUpdateErrors,
  UsersControllerUpdateResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * User Login
 *
 * Authenticates a user.
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerLoginResponses,
    AuthControllerLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Switch to another company context
 */
export const authControllerSwitchCompany = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerSwitchCompanyData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerSwitchCompanyResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/switch-company",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Invalidates the current session and clears tokens.
 */
export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    AuthControllerLogoutResponses,
    AuthControllerLogoutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/logout",
    ...options,
  });

/**
 * Logout from all devices
 *
 * Invalidates all active sessions for the current user.
 */
export const authControllerLogoutAll = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutAllData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    AuthControllerLogoutAllResponses,
    AuthControllerLogoutAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/logout-all",
    ...options,
  });

/**
 * Refresh Tokens
 *
 * Generates new access and refresh tokens using a valid refresh token.
 */
export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerRefreshData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    AuthControllerRefreshResponses,
    AuthControllerRefreshErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/refresh",
    ...options,
  });

/**
 * Get Active Sessions
 *
 * Retrieves a list of all active sessions for the current user.
 */
export const authControllerGetSessions = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerGetSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AuthControllerGetSessionsResponses,
    AuthControllerGetSessionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/sessions",
    ...options,
  });

/**
 * Revoke Session
 *
 * Terminates a specific session using its unique identifier (jti).
 */
export const authControllerRevokeSession = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerRevokeSessionData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    AuthControllerRevokeSessionResponses,
    AuthControllerRevokeSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/sessions/{jti}",
    ...options,
  });

/**
 * Request password reset email
 */
export const authControllerForgotPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerForgotPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerForgotPasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset password using token from email
 */
export const authControllerResetPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerResetPasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Staff accepts invitation and creates account
 */
export const usersControllerCreateStaff = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersControllerCreateStaffData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UsersControllerCreateStaffResponses,
    UsersControllerCreateStaffErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/api/v1/users/register-staff",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Admin accepts invitation and creates account
 */
export const usersControllerCreateAdmin = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersControllerCreateAdminData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UsersControllerCreateAdminResponses,
    UsersControllerCreateAdminErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/api/v1/users/register-admin",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Admin invites staff to their company
 */
export const usersControllerInviteStaff = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersControllerInviteStaffData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UsersControllerInviteStaffResponses,
    UsersControllerInviteStaffErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/invite-staff",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Get all staff in your company
 */
export const usersControllerFindCompanyStaff = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UsersControllerFindCompanyStaffData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UsersControllerFindCompanyStaffResponses,
    UsersControllerFindCompanyStaffErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/company",
    ...options,
  });

/**
 * Get user by UUID (Admin)
 */
export const usersControllerFindOneByCompany = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UsersControllerFindOneByCompanyData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    UsersControllerFindOneByCompanyResponses,
    UsersControllerFindOneByCompanyErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{uuid}",
    ...options,
  });

/**
 * Update user by UUID
 */
export const usersControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsersControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersControllerUpdateResponses,
    UsersControllerUpdateErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Super Admin invites a company admin/owner
 */
export const superadminUsersControllerInviteAdmin = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperadminUsersControllerInviteAdminData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SuperadminUsersControllerInviteAdminResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/users/invite-admin",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Get all users (platform-level)
 */
export const superadminUsersControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperadminUsersControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SuperadminUsersControllerFindAllResponses,
    SuperadminUsersControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/users",
    ...options,
  });

/**
 * Soft delete user by UUID
 */
export const superadminUsersControllerDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperadminUsersControllerDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    SuperadminUsersControllerDeleteResponses,
    SuperadminUsersControllerDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/users/{uuid}",
    ...options,
  });

/**
 * Get user by UUID (Super Admin)
 */
export const superadminUsersControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperadminUsersControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SuperadminUsersControllerFindOneResponses,
    SuperadminUsersControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/users/{uuid}",
    ...options,
  });

/**
 * Restore a soft-deleted user
 */
export const superadminUsersControllerRestore = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperadminUsersControllerRestoreData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SuperadminUsersControllerRestoreResponses,
    SuperadminUsersControllerRestoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/users/{uuid}/restore",
    ...options,
  });

/**
 * Preview invitation details without accepting
 */
export const invitesControllerPreviewInvite = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvitesControllerPreviewInviteData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    InvitesControllerPreviewInviteResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/invites/preview", ...options });

/**
 * Accept invitation (existing authenticated users)
 */
export const invitesControllerAcceptInvite = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvitesControllerAcceptInviteData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvitesControllerAcceptInviteResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invites/accept",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Create a new company (User becomes ADMIN)
 *
 * Creates a company and establishes an ADMIN membership for the creator. Requires token refresh after creation.
 */
export const companiesControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<CompaniesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CompaniesControllerCreateResponses,
    CompaniesControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/companies",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all companies where I am a member
 *
 * Returns list of companies user belongs to via memberships
 */
export const companiesControllerGetMyCompanies = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CompaniesControllerGetMyCompaniesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CompaniesControllerGetMyCompaniesResponses,
    CompaniesControllerGetMyCompaniesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/companies/my-companies",
    ...options,
  });

/**
 * Get current company statistics
 *
 * Returns stats for the currently active company in JWT
 */
export const companiesControllerGetCurrentCompanyStats = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    CompaniesControllerGetCurrentCompanyStatsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    CompaniesControllerGetCurrentCompanyStatsResponses,
    CompaniesControllerGetCurrentCompanyStatsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/companies/current/stats",
    ...options,
  });

/**
 * Get company by UUID
 */
export const companiesControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompaniesControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CompaniesControllerFindOneResponses,
    CompaniesControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/companies/{uuid}",
    ...options,
  });

/**
 * Update company by UUID (ADMIN only)
 *
 * Updates company details. Requires ADMIN membership.
 */
export const companiesControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CompaniesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    CompaniesControllerUpdateResponses,
    CompaniesControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/companies/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all companies (SUPER_ADMIN only)
 */
export const superAdminCompaniesControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperAdminCompaniesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SuperAdminCompaniesControllerFindAllResponses,
    SuperAdminCompaniesControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/companies",
    ...options,
  });

/**
 * Soft delete company by UUID (SUPER_ADMIN only)
 */
export const superAdminCompaniesControllerDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperAdminCompaniesControllerDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    SuperAdminCompaniesControllerDeleteResponses,
    SuperAdminCompaniesControllerDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/companies/{uuid}",
    ...options,
  });

/**
 * Restore company by UUID (SUPER_ADMIN only)
 */
export const superAdminCompaniesControllerRestore = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperAdminCompaniesControllerRestoreData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    SuperAdminCompaniesControllerRestoreResponses,
    SuperAdminCompaniesControllerRestoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/companies/{uuid}/restore",
    ...options,
  });

/**
 * Toggle company active/inactive status (SUPER_ADMIN only)
 */
export const superAdminCompaniesControllerToggleStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperAdminCompaniesControllerToggleStatusData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    SuperAdminCompaniesControllerToggleStatusResponses,
    SuperAdminCompaniesControllerToggleStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/companies/{uuid}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get current user membership details
 */
export const membershipsControllerGetMyMembership = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MembershipsControllerGetMyMembershipData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MembershipsControllerGetMyMembershipResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/memberships/me",
    ...options,
  });

/**
 * List all members of a company
 */
export const membershipsControllerGetMembers = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MembershipsControllerGetMembersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MembershipsControllerGetMembersResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/memberships/company/{companyUuid}/members",
    ...options,
  });

/**
 * Remove a member from the company
 */
export const membershipsControllerRemoveMember = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MembershipsControllerRemoveMemberData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MembershipsControllerRemoveMemberResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/memberships/{membershipUuid}",
    ...options,
  });

/**
 * Update member role
 */
export const membershipsControllerUpdateMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MembershipsControllerUpdateMembershipData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    MembershipsControllerUpdateMembershipResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/memberships/{membershipUuid}",
    ...options,
  });

/**
 * List all SuperAdmin audit log entries
 */
export const platformAuditControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PlatformAuditControllerFindAllData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformAuditControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/admin/audit-logs",
    ...options,
  });

/**
 * List invoices with optional search filters
 */
export const invoicesControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<InvoicesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    InvoicesControllerFindAllResponses,
    InvoicesControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices",
    ...options,
  });

/**
 * Create a new invoice with line items
 *
 * Creates an invoice (DRAFT status) and its items atomically. Returns invoice with UUID for subsequent operations.
 */
export const invoicesControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<InvoicesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerCreateResponses,
    InvoicesControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Export invoices as CSV or XLSX (Admin only, max 10,000 rows)
 */
export const invoicesControllerExportInvoices = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerExportInvoicesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    InvoicesControllerExportInvoicesResponses,
    InvoicesControllerExportInvoicesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/export",
    ...options,
  });

/**
 * Finalize multiple invoices and queue PDF generation
 *
 * Finalizes multiple DRAFT invoices atomically. Valid invoices are assigned invoice numbers and queued for PDF generation. Returns detailed results for each invoice.
 */
export const invoicesControllerBulkFinalize = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerBulkFinalizeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerBulkFinalizeResponses,
    InvoicesControllerBulkFinalizeErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/bulk/finalize",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Send multiple invoices via email
 *
 * Validates and queues multiple invoices for email delivery. Invoices must be finalized and have PDF URLs. Returns detailed results for each invoice.
 */
export const invoicesControllerBulkSend = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerBulkSendData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerBulkSendResponses,
    InvoicesControllerBulkSendErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/bulk/send",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete invoice (DRAFT only)
 */
export const invoicesControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<InvoicesControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    InvoicesControllerRemoveResponses,
    InvoicesControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}",
    ...options,
  });

/**
 * Get invoice by UUID with full details
 */
export const invoicesControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<InvoicesControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    InvoicesControllerFindOneResponses,
    InvoicesControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}",
    ...options,
  });

/**
 * Update invoice (DRAFT status only)
 */
export const invoicesControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<InvoicesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    InvoicesControllerUpdateResponses,
    InvoicesControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Finalize invoice and generate invoice number
 */
export const invoicesControllerFinalize = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerFinalizeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerFinalizeResponses,
    InvoicesControllerFinalizeErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/finalize",
    ...options,
  });

/**
 * Generate and download invoice PDF (DEMO)
 */
export const invoicesControllerDownloadDemoPdf = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerDownloadDemoPdfData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    InvoicesControllerDownloadDemoPdfResponses,
    InvoicesControllerDownloadDemoPdfErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/pdf/demo",
    ...options,
  });

/**
 * Send invoice to customer (async via queue)
 *
 * Queues invoice for PDF generation, S3 upload, and email delivery. Returns immediately.
 */
export const invoicesControllerSend = <ThrowOnError extends boolean = false>(
  options: Options<InvoicesControllerSendData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerSendResponses,
    InvoicesControllerSendErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/send",
    ...options,
  });

/**
 * Resend invoice email to customer
 *
 * Resends invoice email directly. Invoice must be FINALIZED or SENT and have a PDF URL.
 */
export const invoicesControllerResendEmail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerResendEmailData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerResendEmailResponses,
    InvoicesControllerResendEmailErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/resend-email",
    ...options,
  });

/**
 * Submit e-invoice to LHDN MyInvois
 *
 * Digitally signs the invoice using the company X.509 certificate and creates a submission record. Invoice must be in FINALIZED status. Supports both CA-issued and self-signed certificates (sandbox).
 */
export const invoicesControllerSubmitEinvoice = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerSubmitEinvoiceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerSubmitEinvoiceResponses,
    InvoicesControllerSubmitEinvoiceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/submit-einvoice",
    ...options,
  });

/**
 * Void invoice
 */
export const invoicesControllerVoid = <ThrowOnError extends boolean = false>(
  options: Options<InvoicesControllerVoidData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerVoidResponses,
    InvoicesControllerVoidErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/void",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Cancel a submitted/accepted LHDN document
 */
export const invoicesControllerCancelLhdn = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerCancelLhdnData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerCancelLhdnResponses,
    InvoicesControllerCancelLhdnErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/cancel-lhdn",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get invoice audit trail
 */
export const invoicesControllerGetAuditTrail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerGetAuditTrailData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    InvoicesControllerGetAuditTrailResponses,
    InvoicesControllerGetAuditTrailErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/audit-trail",
    ...options,
  });

/**
 * Clone an invoice as a new DRAFT
 */
export const invoicesControllerCloneInvoice = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerCloneInvoiceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoicesControllerCloneInvoiceResponses,
    InvoicesControllerCloneInvoiceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/clone",
    ...options,
  });

/**
 * Get allowed status transitions for this invoice
 */
export const invoicesControllerGetAllowedTransitions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoicesControllerGetAllowedTransitionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    InvoicesControllerGetAllowedTransitionsResponses,
    InvoicesControllerGetAllowedTransitionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/allowed-transitions",
    ...options,
  });

/**
 * Get all customers with pagination
 */
export const customersControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CustomersControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CustomersControllerFindAllResponses,
    CustomersControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers",
    ...options,
  });

/**
 * Create a new customer
 */
export const customersControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<CustomersControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CustomersControllerCreateResponses,
    CustomersControllerCreateErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Bulk upload customers via CSV
 */
export const customersControllerBulkUpload = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CustomersControllerBulkUploadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CustomersControllerBulkUploadResponses,
    CustomersControllerBulkUploadErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/bulk-upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Track CSV import progress (SSE)
 */
export const customersControllerTrackProgress = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CustomersControllerTrackProgressData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CustomersControllerTrackProgressResponses,
    CustomersControllerTrackProgressErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/bulk-upload/progress/{jobId}",
    ...options,
  });

/**
 * Get CSV import status (polling alternative)
 */
export const customersControllerGetUploadStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CustomersControllerGetUploadStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CustomersControllerGetUploadStatusResponses,
    CustomersControllerGetUploadStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/bulk-upload/status/{jobId}",
    ...options,
  });

/**
 * Download error report using secure token
 */
export const customersControllerDownloadErrors = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CustomersControllerDownloadErrorsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CustomersControllerDownloadErrorsResponses,
    CustomersControllerDownloadErrorsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/bulk-upload/errors/{errorToken}",
    ...options,
  });

/**
 * Soft delete customer by UUID
 */
export const customersControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<CustomersControllerDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CustomersControllerDeleteResponses,
    CustomersControllerDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/{uuid}",
    ...options,
  });

/**
 * Get customer by UUID
 */
export const customersControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CustomersControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CustomersControllerFindOneResponses,
    CustomersControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/{uuid}",
    ...options,
  });

/**
 * Update customer by UUID
 */
export const customersControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CustomersControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    CustomersControllerUpdateResponses,
    CustomersControllerUpdateErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Restore customer by UUID
 */
export const customersControllerRestore = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CustomersControllerRestoreData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    CustomersControllerRestoreResponses,
    CustomersControllerRestoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/customers/{uuid}/restore",
    ...options,
  });

/**
 * Get all official MyInvois classification codes
 *
 * Returns the complete list of LHDN-approved classification codes for product categorization
 */
export const productsControllerGetClassificationCodes = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ProductsControllerGetClassificationCodesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ProductsControllerGetClassificationCodesResponses,
    ProductsControllerGetClassificationCodesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/products/classification-codes",
    ...options,
  });

/**
 * Get all products for the current company
 *
 * Supports pagination, searching (SKU/Name), and sorting.
 */
export const productsControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<ProductsControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ProductsControllerFindAllResponses,
    ProductsControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/products",
    ...options,
  });

/**
 * Create a new product for the current company
 *
 * Creates a product scoped to the active company. SKU is auto-generated in format: PRD-YYYYMM-XXXXX.
 */
export const productsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ProductsControllerCreateResponses,
    ProductsControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Soft delete a product by UUID from the current company
 */
export const productsControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<ProductsControllerDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ProductsControllerDeleteResponses,
    ProductsControllerDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/products/{uuid}",
    ...options,
  });

/**
 * Get a specific product by UUID from the current company
 */
export const productsControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<ProductsControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ProductsControllerFindOneResponses,
    ProductsControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/products/{uuid}",
    ...options,
  });

/**
 * Update a product by UUID within the current company
 *
 * SKU cannot be modified after creation.
 */
export const productsControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    ProductsControllerUpdateResponses,
    ProductsControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/products/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Restore a soft-deleted product by UUID in the current company
 */
export const productsControllerRestore = <ThrowOnError extends boolean = false>(
  options: Options<ProductsControllerRestoreData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    ProductsControllerRestoreResponses,
    ProductsControllerRestoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/products/{uuid}/restore",
    ...options,
  });

/**
 * Get all products (SUPER_ADMIN only)
 */
export const superadminProductsControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SuperadminProductsControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    SuperadminProductsControllerFindAllResponses,
    SuperadminProductsControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/products",
    ...options,
  });

/**
 * Soft delete product by UUID (SUPER_ADMIN only)
 */
export const superadminProductsControllerDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperadminProductsControllerDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    SuperadminProductsControllerDeleteResponses,
    SuperadminProductsControllerDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/products/{uuid}",
    ...options,
  });

/**
 * Get product by UUID (SUPER_ADMIN only)
 */
export const superadminProductsControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperadminProductsControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SuperadminProductsControllerFindOneResponses,
    SuperadminProductsControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/products/{uuid}",
    ...options,
  });

/**
 * Restore product by UUID (SUPER_ADMIN only)
 */
export const superadminProductsControllerRestore = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SuperadminProductsControllerRestoreData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    SuperadminProductsControllerRestoreResponses,
    SuperadminProductsControllerRestoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/products/{uuid}/restore",
    ...options,
  });

/**
 * Get all tax rules for your company
 *
 * Returns System Defaults + Your Company Rules only. Cannot see other companies.
 */
export const taxRulesControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<TaxRulesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TaxRulesControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-rules",
    ...options,
  });

/**
 * Create a company-specific tax rule
 *
 * Company Admins can create tax rules for their own company. The system enforces tenant isolation.
 */
export const taxRulesControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<TaxRulesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TaxRulesControllerCreateResponses,
    TaxRulesControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-rules",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete your company tax rule
 *
 * Can only delete rules belonging to your company. System defaults cannot be deleted.
 */
export const taxRulesControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<TaxRulesControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TaxRulesControllerRemoveResponses,
    TaxRulesControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-rules/{uuid}",
    ...options,
  });

/**
 * Get a tax rule by UUID
 *
 * Only returns if it is a system default or belongs to your company.
 */
export const taxRulesControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<TaxRulesControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TaxRulesControllerFindOneResponses,
    TaxRulesControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-rules/{uuid}",
    ...options,
  });

/**
 * Update your company tax rule
 *
 * Can only update rules belonging to your company. System defaults are read-only.
 */
export const taxRulesControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TaxRulesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TaxRulesControllerUpdateResponses,
    TaxRulesControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-rules/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * [SUPERADMIN] Get all tax rules
 *
 * If companyUuid is provided, returns System + Company rules. Otherwise, returns only System Defaults.
 */
export const taxRulesSuperAdminControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TaxRulesSuperAdminControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TaxRulesSuperAdminControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-rules",
    ...options,
  });

/**
 * [SUPERADMIN] Create a tax rule
 *
 * Super Admins can create Global (System) rules or Company-specific rules by providing companyUuid.
 */
export const taxRulesSuperAdminControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxRulesSuperAdminControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TaxRulesSuperAdminControllerCreateResponses,
    TaxRulesSuperAdminControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-rules",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * [SUPERADMIN] Delete any tax rule
 *
 * No tenant restrictions. Can delete any rule.
 */
export const taxRulesSuperAdminControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxRulesSuperAdminControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TaxRulesSuperAdminControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-rules/{uuid}",
    ...options,
  });

/**
 * [SUPERADMIN] Get any tax rule by UUID
 *
 * No tenant restrictions. Can view any rule.
 */
export const taxRulesSuperAdminControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxRulesSuperAdminControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TaxRulesSuperAdminControllerFindOneResponses,
    TaxRulesSuperAdminControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-rules/{uuid}",
    ...options,
  });

/**
 * [SUPERADMIN] Update any tax rule
 *
 * No tenant restrictions. Can update any rule.
 */
export const taxRulesSuperAdminControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxRulesSuperAdminControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TaxRulesSuperAdminControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-rules/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Check LHDN credential status for current company
 *
 * Returns whether LHDN credentials are configured (does NOT return actual credentials)
 */
export const lhdnCredentialsControllerGetCredentialStatus = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    LhdnCredentialsControllerGetCredentialStatusData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    LhdnCredentialsControllerGetCredentialStatusResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn-credentials/status",
    ...options,
  });

/**
 * Deactivate LHDN credentials
 *
 * Marks credentials as inactive (does not delete for audit trail)
 */
export const lhdnCredentialsControllerDeactivateCredentials = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    LhdnCredentialsControllerDeactivateCredentialsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).delete<
    LhdnCredentialsControllerDeactivateCredentialsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn-credentials",
    ...options,
  });

/**
 * Configure LHDN credentials for current company
 *
 * Encrypts and stores LHDN MyInvois credentials. ADMIN only.
 */
export const lhdnCredentialsControllerCreateCredentials = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    LhdnCredentialsControllerCreateCredentialsData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    LhdnCredentialsControllerCreateCredentialsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn-credentials",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update LHDN credentials
 *
 * Updates existing credentials (e.g., certificate renewal)
 */
export const lhdnCredentialsControllerUpdateCredentials = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    LhdnCredentialsControllerUpdateCredentialsData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    LhdnCredentialsControllerUpdateCredentialsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn-credentials",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Validate LHDN credentials by testing API connection
 *
 * Tests connection to LHDN MyInvois API without exposing credentials
 */
export const lhdnCredentialsControllerValidateCredentials = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    LhdnCredentialsControllerValidateCredentialsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    LhdnCredentialsControllerValidateCredentialsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn-credentials/validate",
    ...options,
  });

/**
 * Get audit log for LHDN credential access
 *
 * Returns history of credential access for security monitoring
 */
export const lhdnCredentialsControllerGetAuditLog = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LhdnCredentialsControllerGetAuditLogData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    LhdnCredentialsControllerGetAuditLogResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn-credentials/audit-log",
    ...options,
  });

export const eInvoiceSubmissionsControllerListSubmissions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    EInvoiceSubmissionsControllerListSubmissionsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    EInvoiceSubmissionsControllerListSubmissionsResponses,
    unknown,
    ThrowOnError
  >({ url: "/e-invoice-submissions", ...options });

export const eInvoiceSubmissionsControllerGetStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EInvoiceSubmissionsControllerGetStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    EInvoiceSubmissionsControllerGetStatusResponses,
    unknown,
    ThrowOnError
  >({ url: "/e-invoice-submissions/{uuid}/status", ...options });

export const eInvoiceSubmissionsControllerGetQrCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EInvoiceSubmissionsControllerGetQrCodeData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    EInvoiceSubmissionsControllerGetQrCodeResponses,
    unknown,
    ThrowOnError
  >({ url: "/e-invoice-submissions/{uuid}/qr-code", ...options });

export const eInvoiceSubmissionsControllerRetry = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EInvoiceSubmissionsControllerRetryData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    EInvoiceSubmissionsControllerRetryResponses,
    unknown,
    ThrowOnError
  >({ url: "/e-invoice-submissions/{uuid}/retry", ...options });

/**
 * LHDN status push notification webhook
 */
export const lhdnWebhookControllerHandleWebhook = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LhdnWebhookControllerHandleWebhookData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LhdnWebhookControllerHandleWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: "/webhooks/lhdn", ...options });

export const lhdnWebhookControllerHealthCheck = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LhdnWebhookControllerHealthCheckData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    LhdnWebhookControllerHealthCheckResponses,
    unknown,
    ThrowOnError
  >({ url: "/webhooks/lhdn/health", ...options });

/**
 * List synced LHDN notifications for current company
 */
export const lhdnManagementControllerListNotifications = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    LhdnManagementControllerListNotificationsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    LhdnManagementControllerListNotificationsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn/notifications",
    ...options,
  });

/**
 * Trigger immediate notification sync for current company
 */
export const lhdnManagementControllerSyncNotifications = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    LhdnManagementControllerSyncNotificationsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    LhdnManagementControllerSyncNotificationsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn/notifications/sync",
    ...options,
  });

/**
 * Get LHDN document types (cached 24h)
 */
export const lhdnManagementControllerGetDocumentTypes = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LhdnManagementControllerGetDocumentTypesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    LhdnManagementControllerGetDocumentTypesResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/lhdn/document-types",
    ...options,
  });

/**
 * List all invoice templates for the current company
 */
export const invoiceTemplatesControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<InvoiceTemplatesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    InvoiceTemplatesControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoice-templates",
    ...options,
  });

/**
 * Create an invoice template
 */
export const invoiceTemplatesControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoiceTemplatesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InvoiceTemplatesControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoice-templates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an invoice template
 */
export const invoiceTemplatesControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoiceTemplatesControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    InvoiceTemplatesControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoice-templates/{uuid}",
    ...options,
  });

/**
 * Get a single invoice template
 */
export const invoiceTemplatesControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoiceTemplatesControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    InvoiceTemplatesControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoice-templates/{uuid}",
    ...options,
  });

/**
 * Update an invoice template
 */
export const invoiceTemplatesControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoiceTemplatesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    InvoiceTemplatesControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoice-templates/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Set a template as the default for invoices
 */
export const invoiceTemplatesControllerSetDefault = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InvoiceTemplatesControllerSetDefaultData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    InvoiceTemplatesControllerSetDefaultResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoice-templates/{uuid}/set-default",
    ...options,
  });

/**
 * Get all tax categories for your company
 *
 * Returns System Defaults + Your Company Categories only. Cannot see other companies.
 */
export const taxCategoriesControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TaxCategoriesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TaxCategoriesControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-categories",
    ...options,
  });

/**
 * Create a company-specific tax category
 *
 * Company Admins can create tax categories for their own company. The system enforces tenant isolation.
 */
export const taxCategoriesControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TaxCategoriesControllerCreateResponses,
    TaxCategoriesControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete your company tax category
 *
 * Can only delete categories belonging to your company. System defaults cannot be deleted.
 */
export const taxCategoriesControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TaxCategoriesControllerRemoveResponses,
    TaxCategoriesControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-categories/{uuid}",
    ...options,
  });

/**
 * Get a tax category by UUID
 *
 * Only returns if it is a system default or belongs to your company.
 */
export const taxCategoriesControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TaxCategoriesControllerFindOneResponses,
    TaxCategoriesControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-categories/{uuid}",
    ...options,
  });

/**
 * Update your company tax category
 *
 * Can only update categories belonging to your company. System defaults are read-only.
 */
export const taxCategoriesControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TaxCategoriesControllerUpdateResponses,
    TaxCategoriesControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tax-categories/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * [SUPERADMIN] Get all tax categories
 *
 * If companyUuid is provided, returns System + Company categories. Otherwise, returns only System Defaults.
 */
export const taxCategoriesSuperAdminControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TaxCategoriesSuperAdminControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TaxCategoriesSuperAdminControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-categories",
    ...options,
  });

/**
 * [SUPERADMIN] Create a tax category
 *
 * Super Admins can create Global (System) categories or Company-specific categories by providing companyUuid.
 */
export const taxCategoriesSuperAdminControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesSuperAdminControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TaxCategoriesSuperAdminControllerCreateResponses,
    TaxCategoriesSuperAdminControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * [SUPERADMIN] Delete any tax category
 *
 * No tenant restrictions. Can delete any category.
 */
export const taxCategoriesSuperAdminControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesSuperAdminControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TaxCategoriesSuperAdminControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-categories/{uuid}",
    ...options,
  });

/**
 * [SUPERADMIN] Get any tax category by UUID
 *
 * No tenant restrictions. Can view any category.
 */
export const taxCategoriesSuperAdminControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesSuperAdminControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TaxCategoriesSuperAdminControllerFindOneResponses,
    TaxCategoriesSuperAdminControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-categories/{uuid}",
    ...options,
  });

/**
 * [SUPERADMIN] Update any tax category
 *
 * No tenant restrictions. Can update any category.
 */
export const taxCategoriesSuperAdminControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TaxCategoriesSuperAdminControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    TaxCategoriesSuperAdminControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/tax-categories/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Health check — database + redis + memory
 */
export const healthControllerCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthControllerCheckData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthControllerCheckResponses,
    HealthControllerCheckErrors,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * Get payments for an invoice
 */
export const paymentsControllerGetPayments = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerGetPaymentsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PaymentsControllerGetPaymentsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/payments",
    ...options,
  });

/**
 * Record a payment for an invoice
 */
export const paymentsControllerRecordPayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerRecordPaymentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PaymentsControllerRecordPaymentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/payments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get outstanding balance for an invoice
 */
export const paymentsControllerGetBalance = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerGetBalanceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PaymentsControllerGetBalanceResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{uuid}/payments/balance",
    ...options,
  });

/**
 * Delete a payment record
 */
export const paymentsControllerDeletePayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsControllerDeletePaymentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PaymentsControllerDeletePaymentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/invoices/{invoiceUuid}/payments/{paymentUuid}",
    ...options,
  });

/**
 * Request approval for an invoice
 */
export const approvalsControllerRequestApproval = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApprovalsControllerRequestApprovalData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApprovalsControllerRequestApprovalResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/approvals/invoices/{uuid}/request",
    ...options,
  });

/**
 * Approve or reject an approval request
 */
export const approvalsControllerReviewApproval = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApprovalsControllerReviewApprovalData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApprovalsControllerReviewApprovalResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/approvals/{approvalUuid}/review",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get approvals for an invoice
 */
export const approvalsControllerGetByInvoice = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApprovalsControllerGetByInvoiceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApprovalsControllerGetByInvoiceResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/approvals/invoices/{uuid}",
    ...options,
  });

/**
 * Get all pending approvals for my company
 */
export const approvalsControllerGetPending = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApprovalsControllerGetPendingData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApprovalsControllerGetPendingResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/approvals/pending",
    ...options,
  });

/**
 * Get invoice dashboard summary
 */
export const analyticsControllerGetDashboard = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AnalyticsControllerGetDashboardData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AnalyticsControllerGetDashboardResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/analytics/dashboard",
    ...options,
  });

/**
 * Get monthly revenue breakdown
 */
export const analyticsControllerGetMonthlyRevenue = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AnalyticsControllerGetMonthlyRevenueData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AnalyticsControllerGetMonthlyRevenueResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/analytics/revenue/monthly",
    ...options,
  });

/**
 * Get accounts receivable aging report
 */
export const analyticsControllerGetAgingReport = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AnalyticsControllerGetAgingReportData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AnalyticsControllerGetAgingReportResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/analytics/aging",
    ...options,
  });

/**
 * Get LHDN e-invoice submission report
 */
export const analyticsControllerGetLhdnReport = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AnalyticsControllerGetLhdnReportData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AnalyticsControllerGetLhdnReportResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/analytics/lhdn",
    ...options,
  });

/**
 * Get platform-wide overview metrics
 */
export const superAdminAnalyticsControllerGetPlatformOverview = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SuperAdminAnalyticsControllerGetPlatformOverviewData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SuperAdminAnalyticsControllerGetPlatformOverviewResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/analytics/platform-overview",
    ...options,
  });

/**
 * Get platform-wide revenue breakdown by period
 */
export const superAdminAnalyticsControllerGetPlatformRevenue = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SuperAdminAnalyticsControllerGetPlatformRevenueData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SuperAdminAnalyticsControllerGetPlatformRevenueResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/analytics/revenue",
    ...options,
  });

/**
 * Get top companies by revenue
 */
export const superAdminAnalyticsControllerGetTopCompanies = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SuperAdminAnalyticsControllerGetTopCompaniesData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SuperAdminAnalyticsControllerGetTopCompaniesResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/analytics/top-companies",
    ...options,
  });

/**
 * Get credit memos for an invoice
 */
export const creditMemosControllerFindByInvoice = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreditMemosControllerFindByInvoiceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CreditMemosControllerFindByInvoiceResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/credit-memos/invoices/{uuid}",
    ...options,
  });

/**
 * Create a credit memo for an invoice
 */
export const creditMemosControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreditMemosControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreditMemosControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/credit-memos/invoices/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Issue a credit memo
 */
export const creditMemosControllerIssue = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreditMemosControllerIssueData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreditMemosControllerIssueResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/credit-memos/{memoUuid}/issue",
    ...options,
  });

/**
 * Void a credit memo
 */
export const creditMemosControllerVoid = <ThrowOnError extends boolean = false>(
  options: Options<CreditMemosControllerVoidData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    CreditMemosControllerVoidResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/credit-memos/{memoUuid}/void",
    ...options,
  });

/**
 * List quotations with optional status filter
 */
export const quotationsControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<QuotationsControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    QuotationsControllerFindAllResponses,
    QuotationsControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations",
    ...options,
  });

/**
 * Create a new quotation
 */
export const quotationsControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    QuotationsControllerCreateResponses,
    QuotationsControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete quotation (DRAFT only)
 */
export const quotationsControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    QuotationsControllerRemoveResponses,
    QuotationsControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}",
    ...options,
  });

/**
 * Get quotation by UUID
 */
export const quotationsControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    QuotationsControllerFindOneResponses,
    QuotationsControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}",
    ...options,
  });

/**
 * Update quotation (DRAFT only)
 */
export const quotationsControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    QuotationsControllerUpdateResponses,
    QuotationsControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Send quotation to customer
 */
export const quotationsControllerSend = <ThrowOnError extends boolean = false>(
  options: Options<QuotationsControllerSendData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    QuotationsControllerSendResponses,
    QuotationsControllerSendErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}/send",
    ...options,
  });

/**
 * Create a new revision of a SENT quotation
 */
export const quotationsControllerRevise = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerReviseData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    QuotationsControllerReviseResponses,
    QuotationsControllerReviseErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}/revise",
    ...options,
  });

/**
 * Accept a SENT quotation
 */
export const quotationsControllerAccept = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerAcceptData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    QuotationsControllerAcceptResponses,
    QuotationsControllerAcceptErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}/accept",
    ...options,
  });

/**
 * Reject a SENT quotation
 */
export const quotationsControllerReject = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerRejectData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    QuotationsControllerRejectResponses,
    QuotationsControllerRejectErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}/reject",
    ...options,
  });

/**
 * Convert an ACCEPTED or SENT quotation to a DRAFT invoice
 */
export const quotationsControllerConvertToInvoice = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QuotationsControllerConvertToInvoiceData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    QuotationsControllerConvertToInvoiceResponses,
    QuotationsControllerConvertToInvoiceErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/quotations/{uuid}/convert-to-invoice",
    ...options,
  });

/**
 * List all recurring invoice plans for the company
 */
export const recurringInvoicesControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RecurringInvoicesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    RecurringInvoicesControllerFindAllResponses,
    RecurringInvoicesControllerFindAllErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/recurring-invoices",
    ...options,
  });

/**
 * Create a new recurring invoice plan
 */
export const recurringInvoicesControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RecurringInvoicesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RecurringInvoicesControllerCreateResponses,
    RecurringInvoicesControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/recurring-invoices",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Cancel (soft-delete) a recurring invoice plan
 */
export const recurringInvoicesControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RecurringInvoicesControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    RecurringInvoicesControllerRemoveResponses,
    RecurringInvoicesControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/recurring-invoices/{uuid}",
    ...options,
  });

/**
 * Get a single recurring invoice plan
 */
export const recurringInvoicesControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RecurringInvoicesControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    RecurringInvoicesControllerFindOneResponses,
    RecurringInvoicesControllerFindOneErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/recurring-invoices/{uuid}",
    ...options,
  });

/**
 * Pause an active recurring invoice plan
 */
export const recurringInvoicesControllerPause = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RecurringInvoicesControllerPauseData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    RecurringInvoicesControllerPauseResponses,
    RecurringInvoicesControllerPauseErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/recurring-invoices/{uuid}/pause",
    ...options,
  });

/**
 * Resume a paused recurring invoice plan
 */
export const recurringInvoicesControllerResume = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RecurringInvoicesControllerResumeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    RecurringInvoicesControllerResumeResponses,
    RecurringInvoicesControllerResumeErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/recurring-invoices/{uuid}/resume",
    ...options,
  });

/**
 * Cancel a recurring invoice plan
 */
export const recurringInvoicesControllerCancel = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RecurringInvoicesControllerCancelData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    RecurringInvoicesControllerCancelResponses,
    RecurringInvoicesControllerCancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/recurring-invoices/{uuid}/cancel",
    ...options,
  });

/**
 * List all invoice audit records across tenants
 */
export const superadminAuditControllerFindAllInvoiceAudits = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SuperadminAuditControllerFindAllInvoiceAuditsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SuperadminAuditControllerFindAllInvoiceAuditsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/audit/invoice-audits",
    ...options,
  });

/**
 * Get single invoice audit record by UUID
 */
export const superadminAuditControllerFindInvoiceAuditByUuid = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SuperadminAuditControllerFindInvoiceAuditByUuidData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    SuperadminAuditControllerFindInvoiceAuditByUuidResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/audit/invoice-audits/{uuid}",
    ...options,
  });

/**
 * List all platform audit logs
 */
export const superadminAuditControllerFindAllPlatformLogs = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SuperadminAuditControllerFindAllPlatformLogsData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SuperadminAuditControllerFindAllPlatformLogsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/audit/platform-logs",
    ...options,
  });

/**
 * Get single platform log by ID
 */
export const superadminAuditControllerFindPlatformLogById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SuperadminAuditControllerFindPlatformLogByIdData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    SuperadminAuditControllerFindPlatformLogByIdResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/audit/platform-logs/{id}",
    ...options,
  });

/**
 * Get all audit events for a specific company
 */
export const superadminAuditControllerGetCompanyTimeline = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SuperadminAuditControllerGetCompanyTimelineData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    SuperadminAuditControllerGetCompanyTimelineResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/superadmin/audit/company/{companyId}/timeline",
    ...options,
  });
