// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type LoginSwaggerDto = {
  /**
   * The email address of the user
   */
  email: string;
  /**
   * The password of the user
   */
  password: string;
  /**
   * The company ID (required if user belongs to multiple companies)
   */
  companyId?: number;
};

export type LoginResponseDto = {
  [key: string]: unknown;
};

export type SwitchCompanySwaggerDto = {
  /**
   * The company ID
   */
  companyId: number;
};

export type ForgotPasswordDto = {
  email: string;
};

export type ResetPasswordDto = {
  token: string;
  newPassword: string;
};

export type CreateUserSwaggerDto = {
  password: string;
  name: string;
  token: string;
  phoneNumber?: string;
};

export type InviteStaffSwaggerDto = {
  /**
   * Email of the staff to invite
   */
  email: string;
};

export type UpdateUserSwaggerDto = {
  /**
   * User full name
   */
  name?: string;
  /**
   * User password (must meet complexity requirements)
   */
  password?: string;
  /**
   * User phone number
   */
  phoneNumber?: string;
  /**
   * User active status
   */
  isActive?: boolean;
};

export type InviteAdminDto = {
  email: string;
};

export type AcceptInviteSwaggerDto = {
  /**
   * The invite token of the user
   */
  inviteToken: string;
};

export type CreateCompanySwaggerDto = {
  /**
   * Full name of the company
   */
  name: string;
  /**
   * Tax Identification Number (Mandatory for MyInvois)
   */
  tin: string;
  /**
   * Business Registration Number / SSM No (Mandatory for MyInvois)
   */
  brn: string;
  /**
   * Malaysia Standard Industrial Classification 5-digit code
   */
  msicCode: string;
  /**
   * Description of business activity associated with MSIC code
   */
  businessActivityDesc: string;
  /**
   * SST Registration Number (Mandatory if tax registered)
   */
  sstRegistrationNumber: string;
  /**
   * Tourism Tax Registration Number
   */
  tourismTaxRegistration?: string;
  /**
   * Primary contact phone number
   */
  phone: string;
  /**
   * Primary contact email address
   */
  email: string;
  /**
   * Bank account number for payments
   */
  bankAccountNumber?: string;
  /**
   * Name of the bank
   */
  bankName?: string;
  /**
   * Address line 1
   */
  addressLine1: string;
  /**
   * Address line 2
   */
  addressLine2?: string;
  /**
   * Postal code
   */
  postalCode: string;
  /**
   * City
   */
  city: string;
  /**
   * State
   */
  state: string;
  /**
   * Country code (ISO 3166-1 alpha-3)
   */
  country?: string;
};

export type UpdateCompanySwaggerDto = {
  /**
   * Full name of the company
   */
  name?: string;
  /**
   * Tax Identification Number (Mandatory for MyInvois)
   */
  tin?: string;
  /**
   * Business Registration Number / SSM No (Mandatory for MyInvois)
   */
  brn?: string;
  /**
   * Malaysia Standard Industrial Classification 5-digit code
   */
  msicCode?: string;
  /**
   * Description of business activity associated with MSIC code
   */
  businessActivityDesc?: string;
  /**
   * SST Registration Number (Mandatory if tax registered)
   */
  sstRegistrationNumber?: string;
  /**
   * Tourism Tax Registration Number
   */
  tourismTaxRegistration?: string;
  /**
   * Primary contact phone number
   */
  phone?: string;
  /**
   * Primary contact email address
   */
  email?: string;
  /**
   * Bank account number for payments
   */
  bankAccountNumber?: string;
  /**
   * Name of the bank
   */
  bankName?: string;
  /**
   * Address line 1
   */
  addressLine1?: string;
  /**
   * Address line 2
   */
  addressLine2?: string;
  /**
   * Postal code
   */
  postalCode?: string;
  /**
   * City
   */
  city?: string;
  /**
   * State
   */
  state?: string;
  /**
   * Country code (ISO 3166-1 alpha-3)
   */
  country?: string;
};

export type ToggleCompanyStatusDto = {
  /**
   * Whether the company should be active
   */
  isActive: boolean;
  /**
   * Reason for toggling company status (audit trail)
   */
  reason: string;
};

export type CreateInvoiceItemDto = {
  /**
   * Product ID
   */
  productId: number;
  /**
   * Quantity of product
   */
  quantity: number;
};

export type CreateInvoiceSwaggerDto = {
  /**
   * Customer ID
   */
  customerId: number;
  /**
   * Company ID
   */
  companyId: number;
  /**
   * Invoice date (YYYY-MM-DD)
   */
  invoiceDate: string;
  /**
   * Currency code (ISO 4217)
   */
  currency?: string;
  /**
   * Bill reference number
   */
  billReferenceNumber?: string;
  /**
   * Prepayment amount (if customer already paid)
   */
  prepaymentAmount?: number;
  /**
   * Prepayment date (YYYY-MM-DD)
   */
  prepaymentDate?: string;
  /**
   * Prepayment reference number
   */
  prepaymentReference?: string;
  /**
   * Invoice type code (e.g., 01 for Invoice)
   */
  invoiceTypeCode?: string;
  /**
   * Payment mode code (e.g., 01 for Cash)
   */
  paymentModeCode?: string;
  /**
   * Is this a consolidated invoice?
   */
  isConsolidated?: boolean;
  /**
   * Payment due date (YYYY-MM-DD)
   */
  paymentDueDate?: string;
  /**
   * Payment terms in days (Net 30, Net 60, etc.)
   */
  paymentTermsDays?: number;
  /**
   * Document type classification code
   */
  invoiceCodeType?: string;
  /**
   * Original e-invoice reference UUID (for credit/debit notes)
   */
  originalEinvoiceReference?: string;
  /**
   * Shipping recipient name override
   */
  shippingRecipientName?: string;
  /**
   * Shipping address line 1 override
   */
  shippingAddressLine1?: string;
  /**
   * Shipping address line 2 override
   */
  shippingAddressLine2?: string;
  /**
   * Shipping city override
   */
  shippingCity?: string;
  /**
   * Shipping state override
   */
  shippingState?: string;
  /**
   * Shipping postal code override
   */
  shippingPostalCode?: string;
  /**
   * Shipping country override (ISO 3166-1 alpha-3)
   */
  shippingCountry?: string;
  /**
   * Array of invoice items (products and quantities)
   */
  items: Array<CreateInvoiceItemDto>;
};

export type BulkFinalizeInvoicesDto = {
  /**
   * Array of invoice UUIDs to finalize
   */
  uuids: Array<Array<unknown>>;
};

export type BulkOperationItemResult = {
  uuid: string;
  status: 'success' | 'failed';
  message?: string;
  /**
   * Only present when status is "failed"
   */
  error?: string;
};

export type BulkOperationResult = {
  results: Array<BulkOperationItemResult>;
  successCount: number;
  failedCount: number;
  totalCount: number;
};

export type BulkSendInvoicesDto = {
  /**
   * Array of invoice UUIDs to send
   */
  uuids: Array<string>;
};

export type UpdateInvoiceItemDto = {
  /**
   * Product ID
   */
  productId: number;
  /**
   * Quantity of product
   */
  quantity: number;
};

export type UpdateInvoiceDto = {
  invoiceDate?: string;
  currency?: string;
  invoiceTypeCode?: string;
  paymentModeCode?: string;
  prepaymentAmount?: number;
  /**
   * Payment due date (YYYY-MM-DD)
   */
  paymentDueDate?: string;
  /**
   * Payment terms in days
   */
  paymentTermsDays?: number;
  /**
   * Payment received date (YYYY-MM-DD)
   */
  paymentReceivedDate?: string;
  /**
   * Payment reference number
   */
  paymentReferenceNumber?: string;
  /**
   * Document type classification code
   */
  invoiceCodeType?: string;
  /**
   * Original e-invoice reference UUID
   */
  originalEinvoiceReference?: string;
  /**
   * Shipping recipient name override
   */
  shippingRecipientName?: string;
  /**
   * Shipping address line 1
   */
  shippingAddressLine1?: string;
  /**
   * Shipping address line 2
   */
  shippingAddressLine2?: string;
  /**
   * Shipping city
   */
  shippingCity?: string;
  /**
   * Shipping state
   */
  shippingState?: string;
  /**
   * Shipping postal code
   */
  shippingPostalCode?: string;
  /**
   * Shipping country (ISO 3166-1 alpha-3)
   */
  shippingCountry?: string;
  items?: Array<UpdateInvoiceItemDto>;
};

export type CreateCustomerSwaggerDto = {
  /**
   * Full name of the customer
   */
  name: string;
  /**
   * Customer contact phone number
   */
  phone: string;
  /**
   * Customer email address
   */
  email: string;
  /**
   * LHDN Tax Identification Number for the buyer
   */
  tin?: string;
  /**
   * Type of ID (NRIC, PASSPORT, BRN, ARMY)
   */
  idType?: string;
  /**
   * The actual NRIC or Passport number
   */
  idNumber?: string;
  /**
   * Address line 1
   */
  addressLine1: string;
  /**
   * Address line 2
   */
  addressLine2?: string;
  /**
   * Postal code
   */
  postalCode?: string;
  /**
   * City
   */
  city: string;
  /**
   * State
   */
  state: string;
  /**
   * Country code (ISO 3166-1 alpha-3)
   */
  country?: string;
};

export type BulkUploadDto = {
  /**
   * CSV file upload
   */
  file: Blob | File;
};

export type UpdateCustomerSwaggerDto = {
  /**
   * Full name of the customer
   */
  name?: string;
  /**
   * Customer contact phone number
   */
  phone?: string;
  /**
   * Customer email address
   */
  email?: string;
  /**
   * LHDN Tax Identification Number for the buyer
   */
  tin?: string;
  /**
   * Type of ID (NRIC, PASSPORT, BRN, ARMY)
   */
  idType?: string;
  /**
   * The actual NRIC or Passport number
   */
  idNumber?: string;
  /**
   * Address line 1
   */
  addressLine1?: string;
  /**
   * Address line 2
   */
  addressLine2?: string;
  /**
   * Postal code
   */
  postalCode?: string;
  /**
   * City
   */
  city?: string;
  /**
   * State
   */
  state?: string;
  /**
   * Country code (ISO 3166-1 alpha-3)
   */
  country?: string;
};

export type CreateProductSwaggerDto = {
  /**
   * Product name
   */
  name: string;
  /**
   * Product description
   */
  description?: string;
  /**
   * Product price (MYR)
   */
  price: number;
  /**
   * LHDN 3-digit Classification Code (validated against official MyInvois list)
   */
  classificationCode?: string;
  /**
   * Harmonized System (HS) tariff code for imports/exports
   */
  productTariffCode?: string;
  /**
   * Country code (ISO 3166-1 alpha-3) where product was manufactured
   */
  countryOfOrigin?: string;
  /**
   * Unit of measure (e.g., UNIT, KG, PIECE, LITRE, HOUR, DAY)
   */
  unitOfMeasureCode?: string;
  /**
   * Initial stock quantity
   */
  inStock?: number;
  /**
   * Tax category UUID to assign to this product
   */
  taxCategoryUuid?: string;
  /**
   * Flag to indicate if the product is tax exempt
   */
  isTaxExempt?: boolean;
  /**
   * Reason for tax exemption (required if isTaxExempt is true)
   */
  taxExemptionReason?: string;
};

export type UpdateProductSwaggerDto = {
  /**
   * Product name
   */
  name?: string;
  /**
   * Product description
   */
  description?: string;
  /**
   * Product price (MYR)
   */
  price?: number;
  /**
   * LHDN 3-digit Classification Code (validated against official MyInvois list)
   */
  classificationCode?: string;
  /**
   * Harmonized System (HS) tariff code for imports/exports
   */
  productTariffCode?: string;
  /**
   * Country code (ISO 3166-1 alpha-3) where product was manufactured
   */
  countryOfOrigin?: string;
  /**
   * Unit of measure (e.g., UNIT, KG, PIECE, LITRE, HOUR, DAY)
   */
  unitOfMeasureCode?: string;
  /**
   * Initial stock quantity
   */
  inStock?: number;
  /**
   * Tax category UUID to assign to this product
   */
  taxCategoryUuid?: string;
  /**
   * Flag to indicate if the product is tax exempt
   */
  isTaxExempt?: boolean;
  /**
   * Reason for tax exemption (required if isTaxExempt is true)
   */
  taxExemptionReason?: string;
};

export type CreateTaxRuleDto = {
  /**
   * UUID of the tax category this rule belongs to
   */
  taxCategoryUuid: string;
  /**
   * Tax rate as percentage
   */
  taxRate: number;
  /**
   * Date this rate becomes active (inclusive)
   */
  effectiveFrom: string;
  /**
   * Date this rate expires (inclusive). NULL = no expiry
   */
  effectiveTo?: string;
  /**
   * Whether this rule is active
   */
  isActive: boolean;
  /**
   * Company UUID for company-specific rule (optional)
   */
  companyUuid?: string;
  /**
   * Notes about this tax rule
   */
  notes?: string;
};

export type UpdateTaxRuleDto = {
  /**
   * UUID of the tax category this rule belongs to
   */
  taxCategoryUuid?: string;
  /**
   * Tax rate as percentage
   */
  taxRate?: number;
  /**
   * Date this rate becomes active (inclusive)
   */
  effectiveFrom?: string;
  /**
   * Date this rate expires (inclusive). NULL = no expiry
   */
  effectiveTo?: string;
  /**
   * Whether this rule is active
   */
  isActive?: boolean;
  /**
   * Company UUID for company-specific rule (optional)
   */
  companyUuid?: string;
  /**
   * Notes about this tax rule
   */
  notes?: string;
};

export type CreateLhdnCredentialDto = {
  /**
   * LHDN MyInvois Client ID
   */
  clientId: string;
  /**
   * LHDN MyInvois Client Secret
   */
  clientSecret: string;
  /**
   * X.509 Certificate in PEM format
   */
  x509Certificate: string;
  /**
   * X.509 Private Key in PEM format
   */
  x509PrivateKey: string;
  /**
   * Certificate serial number
   */
  certificateSerial?: string;
  /**
   * Certificate expiry date
   */
  certificateExpiry?: string;
  /**
   * Certificate issuer
   */
  certificateIssuer?: string;
  /**
   * Environment
   */
  environment: 'SANDBOX' | 'PRODUCTION';
};

export type UpdateLhdnCredentialDto = {
  /**
   * LHDN MyInvois Client ID
   */
  clientId?: string;
  /**
   * LHDN MyInvois Client Secret
   */
  clientSecret?: string;
  /**
   * X.509 Certificate in PEM format
   */
  x509Certificate?: string;
  /**
   * X.509 Private Key in PEM format
   */
  x509PrivateKey?: string;
  /**
   * Certificate serial number
   */
  certificateSerial?: string;
  /**
   * Certificate expiry date
   */
  certificateExpiry?: string;
  /**
   * Certificate issuer
   */
  certificateIssuer?: string;
  /**
   * Environment
   */
  environment?: 'SANDBOX' | 'PRODUCTION';
  /**
   * Update isActive
   */
  isActive?: boolean;
};

export type CreateInvoiceTemplateDto = {
  name: string;
  primaryColor?: string;
  secondaryColor?: string;
  fontFamily?: string;
  showLogo?: boolean;
  showQrCode?: boolean;
  showPaymentTerms?: boolean;
  showBankDetails?: boolean;
  showTaxBreakdown?: boolean;
  showNotes?: boolean;
  showSignatureLine?: boolean;
  headerText?: string;
  footerText?: string;
  termsAndConditions?: string;
  bankDetails?: string;
  autoFillSupplierInfo?: boolean;
  showClassificationCode?: boolean;
  showMsicDescription?: boolean;
  autoAttachQrCode?: boolean;
};

export type UpdateInvoiceTemplateDto = {
  name?: string;
  primaryColor?: string;
  secondaryColor?: string;
  fontFamily?: string;
  showLogo?: boolean;
  showQrCode?: boolean;
  showPaymentTerms?: boolean;
  showBankDetails?: boolean;
  showTaxBreakdown?: boolean;
  showNotes?: boolean;
  showSignatureLine?: boolean;
  headerText?: string;
  footerText?: string;
  termsAndConditions?: string;
  bankDetails?: string;
  autoFillSupplierInfo?: boolean;
  showClassificationCode?: boolean;
  showMsicDescription?: boolean;
  autoAttachQrCode?: boolean;
};

export type CreateTaxCategoryDto = {
  /**
   * Name of the tax category
   */
  name: string;
  /**
   * Description of the tax category
   */
  description?: string;
  /**
   * LHDN Tax Type Code
   */
  taxTypeCode: '01' | '02' | '03' | '04' | '05' | '06' | 'E';
  /**
   * Whether this category is active
   */
  isActive: boolean;
  /**
   * Company UUID for company-specific category (optional)
   */
  companyUuid?: string;
};

export type UpdateTaxCategoryDto = {
  /**
   * Name of the tax category
   */
  name: string;
  /**
   * Description of the tax category
   */
  description?: string;
  /**
   * LHDN Tax Type Code
   */
  taxTypeCode: '01' | '02' | '03' | '04' | '05' | '06' | 'E';
  /**
   * Whether this category is active
   */
  isActive: boolean;
};

export type CreatePaymentDto = {
  amount: number;
  method: 'CASH' | 'BANK_TRANSFER' | 'CHEQUE' | 'ONLINE' | 'OTHER';
  referenceNo?: string;
  paidAt: string;
  notes?: string;
};

export type ReviewApprovalDto = {
  status: 'APPROVED' | 'REJECTED';
  comments?: string;
};

export type CreateCreditMemoDto = {
  amount: number;
  reason: string;
  /**
   * UUID of the LHDN original document for credit note submission
   */
  lhdnOriginalUuid?: string;
};

export type CreateQuotationItemDto = {
  itemDescription?: string;
  /**
   * Product UUID to link
   */
  productUuid?: string;
  quantity: number;
  unitPrice: number;
  taxType?: string;
  taxRate?: number;
  /**
   * LHDN 3-digit classification code
   */
  classificationCode?: string;
  note?: string;
};

export type CreateQuotationDto = {
  /**
   * Customer UUID
   */
  customerUuid?: string;
  validUntil?: string;
  items: Array<CreateQuotationItemDto>;
  notes?: string;
  termsAndConditions?: string;
};

export type UpdateQuotationDto = {
  /**
   * Customer UUID
   */
  customerUuid?: string;
  validUntil?: string;
  items?: Array<CreateQuotationItemDto>;
  notes?: string;
  termsAndConditions?: string;
};

export type CreateRecurringInvoiceDto = {
  /**
   * Name / label for this recurring plan
   */
  name: string;
  /**
   * Company ID
   */
  companyId: number;
  /**
   * Customer ID
   */
  customerId?: number;
  /**
   * Billing frequency
   */
  frequency: 'WEEKLY' | 'MONTHLY' | 'QUARTERLY' | 'YEARLY' | 'CUSTOM';
  /**
   * Cron expression (required when frequency is CUSTOM)
   */
  cronExpression?: string;
  /**
   * Start date (YYYY-MM-DD)
   */
  startDate: string;
  /**
   * End date (YYYY-MM-DD)
   */
  endDate?: string;
  /**
   * Maximum number of invoices to generate
   */
  maxOccurrences?: number;
  /**
   * Auto-finalize generated invoices
   */
  autoFinalize?: boolean;
  /**
   * Auto-send generated invoices
   */
  autoSend?: boolean;
  /**
   * Notes
   */
  notes?: string;
};

export type AuthControllerLoginData = {
  body: LoginSwaggerDto;
  path?: never;
  query?: {
    /**
     * Invitation token (if user is accepting an invite)
     */
    invite_token?: string;
  };
  url: '/api/v1/auth/login';
};

export type AuthControllerLoginErrors = {
  /**
   * Invalid credentials
   */
  401: unknown;
  /**
   * Account is disabled
   */
  403: unknown;
};

export type AuthControllerLoginResponses = {
  /**
   * Login successful
   */
  200: LoginResponseDto;
};

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerSwitchCompanyData = {
  /**
   * Switch company context
   */
  body: SwitchCompanySwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/switch-company';
};

export type AuthControllerSwitchCompanyResponses = {
  /**
   * Switched to company context successfully
   */
  200: unknown;
};

export type AuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type AuthControllerLogoutErrors = {
  /**
   * Bearer token missing or invalid
   */
  401: unknown;
};

export type AuthControllerLogoutResponses = {
  /**
   * Logout successful
   */
  200: unknown;
};

export type AuthControllerLogoutAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout-all';
};

export type AuthControllerLogoutAllErrors = {
  /**
   * Bearer token missing or invalid
   */
  401: unknown;
};

export type AuthControllerLogoutAllResponses = {
  /**
   * Logged out from all devices successfully
   */
  200: unknown;
};

export type AuthControllerRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/refresh';
};

export type AuthControllerRefreshErrors = {
  /**
   * Refresh token missing or invalid
   */
  401: unknown;
};

export type AuthControllerRefreshResponses = {
  /**
   * Tokens refreshed successfully
   */
  200: unknown;
};

export type AuthControllerGetSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/sessions';
};

export type AuthControllerGetSessionsErrors = {
  /**
   * Bearer token missing or invalid
   */
  401: unknown;
};

export type AuthControllerGetSessionsResponses = {
  /**
   * Active sessions retrieved
   */
  200: unknown;
};

export type AuthControllerRevokeSessionData = {
  body?: never;
  path: {
    jti: string;
  };
  query?: never;
  url: '/api/v1/auth/sessions/{jti}';
};

export type AuthControllerRevokeSessionErrors = {
  /**
   * Bearer token missing or invalid
   */
  401: unknown;
  /**
   * Session not found
   */
  404: unknown;
};

export type AuthControllerRevokeSessionResponses = {
  /**
   * Session revoked successfully
   */
  200: unknown;
};

export type AuthControllerForgotPasswordData = {
  body: ForgotPasswordDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
  /**
   * Reset email sent if account exists
   */
  200: unknown;
};

export type AuthControllerResetPasswordData = {
  body: ResetPasswordDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/reset-password';
};

export type AuthControllerResetPasswordResponses = {
  /**
   * Password reset successfully
   */
  200: unknown;
};

export type UsersControllerCreateStaffData = {
  /**
   * Staff registration data with invite token
   */
  body: CreateUserSwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/users/register-staff';
};

export type UsersControllerCreateStaffErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Invalid token or user exists
   */
  422: unknown;
};

export type UsersControllerCreateStaffResponses = {
  /**
   * Staff account created successfully
   */
  201: unknown;
};

export type UsersControllerCreateAdminData = {
  /**
   * Admin registration data with invite token
   */
  body: CreateUserSwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/users/register-admin';
};

export type UsersControllerCreateAdminErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Invalid token or user exists
   */
  422: unknown;
};

export type UsersControllerCreateAdminResponses = {
  /**
   * Admin account created successfully
   */
  201: unknown;
};

export type UsersControllerInviteStaffData = {
  /**
   * Email and role of staff to invite
   */
  body: InviteStaffSwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/users/invite-staff';
};

export type UsersControllerInviteStaffErrors = {
  /**
   * Unauthorized - Admin access required
   */
  401: unknown;
  /**
   * User already exists
   */
  422: unknown;
};

export type UsersControllerInviteStaffResponses = {
  /**
   * Invitation sent successfully
   */
  200: unknown;
};

export type UsersControllerFindCompanyStaffData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number (starts from 1)
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
  };
  url: '/api/v1/users/company';
};

export type UsersControllerFindCompanyStaffErrors = {
  /**
   * Unauthorized - Admin access required
   */
  401: unknown;
};

export type UsersControllerFindCompanyStaffResponses = {
  /**
   * Staff retrieved successfully
   */
  200: unknown;
};

export type UsersControllerFindOneByCompanyData = {
  body?: never;
  path: {
    /**
     * User UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/users/{uuid}';
};

export type UsersControllerFindOneByCompanyErrors = {
  /**
   * Unauthorized - Super Admin access required
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type UsersControllerFindOneByCompanyResponses = {
  /**
   * User found
   */
  200: unknown;
};

export type UsersControllerUpdateData = {
  /**
   * User update data (all fields optional)
   */
  body: UpdateUserSwaggerDto;
  path: {
    /**
     * User UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/users/{uuid}';
};

export type UsersControllerUpdateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Admin access required
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
  /**
   * Update failed
   */
  422: unknown;
};

export type UsersControllerUpdateResponses = {
  /**
   * User updated successfully
   */
  200: unknown;
};

export type SuperadminUsersControllerInviteAdminData = {
  body: InviteAdminDto;
  path?: never;
  query?: never;
  url: '/api/v1/superadmin/users/invite-admin';
};

export type SuperadminUsersControllerInviteAdminResponses = {
  201: unknown;
};

export type SuperadminUsersControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number (starts from 1)
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
  };
  url: '/api/v1/superadmin/users';
};

export type SuperadminUsersControllerFindAllErrors = {
  /**
   * Unauthorized - Super Admin access required
   */
  401: unknown;
};

export type SuperadminUsersControllerFindAllResponses = {
  /**
   * Users retrieved successfully
   */
  200: unknown;
};

export type SuperadminUsersControllerDeleteData = {
  body?: never;
  path: {
    /**
     * User UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/users/{uuid}';
};

export type SuperadminUsersControllerDeleteErrors = {
  /**
   * Unauthorized - Admin access required
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
  /**
   * Delete operation failed
   */
  422: unknown;
};

export type SuperadminUsersControllerDeleteResponses = {
  /**
   * User deleted successfully
   */
  200: unknown;
};

export type SuperadminUsersControllerFindOneData = {
  body?: never;
  path: {
    /**
     * User UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/users/{uuid}';
};

export type SuperadminUsersControllerFindOneErrors = {
  /**
   * Unauthorized - Super Admin access required
   */
  401: unknown;
  /**
   * User not found
   */
  404: unknown;
};

export type SuperadminUsersControllerFindOneResponses = {
  /**
   * User found
   */
  200: unknown;
};

export type SuperadminUsersControllerRestoreData = {
  body?: never;
  path: {
    /**
     * User UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/users/{uuid}/restore';
};

export type SuperadminUsersControllerRestoreErrors = {
  /**
   * User not found
   */
  404: unknown;
};

export type SuperadminUsersControllerRestoreResponses = {
  /**
   * User successfully restored
   */
  200: unknown;
};

export type InvitesControllerPreviewInviteData = {
  body?: never;
  path?: never;
  query: {
    token: string;
  };
  url: '/api/v1/invites/preview';
};

export type InvitesControllerPreviewInviteResponses = {
  200: unknown;
};

export type InvitesControllerAcceptInviteData = {
  body: AcceptInviteSwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/invites/accept';
};

export type InvitesControllerAcceptInviteResponses = {
  201: unknown;
};

export type CompaniesControllerCreateData = {
  /**
   * Company creation data
   */
  body: CreateCompanySwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/companies';
};

export type CompaniesControllerCreateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Email already exists
   */
  422: unknown;
};

export type CompaniesControllerCreateResponses = {
  /**
   * Company successfully created with ADMIN membership
   */
  201: unknown;
};

export type CompaniesControllerGetMyCompaniesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/companies/my-companies';
};

export type CompaniesControllerGetMyCompaniesErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type CompaniesControllerGetMyCompaniesResponses = {
  /**
   * Companies retrieved successfully
   */
  200: unknown;
};

export type CompaniesControllerGetCurrentCompanyStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/companies/current/stats';
};

export type CompaniesControllerGetCurrentCompanyStatsErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type CompaniesControllerGetCurrentCompanyStatsResponses = {
  /**
   * Company stats retrieved
   */
  200: unknown;
};

export type CompaniesControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Company UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/companies/{uuid}';
};

export type CompaniesControllerFindOneErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Company not found
   */
  404: unknown;
};

export type CompaniesControllerFindOneResponses = {
  /**
   * Company found
   */
  200: unknown;
};

export type CompaniesControllerUpdateData = {
  /**
   * Company update data (all fields optional)
   */
  body: UpdateCompanySwaggerDto;
  path: {
    /**
     * Company UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/companies/{uuid}';
};

export type CompaniesControllerUpdateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Company not found
   */
  404: unknown;
  /**
   * Email already in use
   */
  422: unknown;
};

export type CompaniesControllerUpdateResponses = {
  /**
   * Company successfully updated
   */
  200: unknown;
};

export type SuperAdminCompaniesControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number (starts from 1)
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
  };
  url: '/api/v1/superadmin/companies';
};

export type SuperAdminCompaniesControllerFindAllErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type SuperAdminCompaniesControllerFindAllResponses = {
  /**
   * Companies retrieved successfully
   */
  200: unknown;
};

export type SuperAdminCompaniesControllerDeleteData = {
  body?: never;
  path: {
    /**
     * Company UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/companies/{uuid}';
};

export type SuperAdminCompaniesControllerDeleteErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Company not found
   */
  404: unknown;
  /**
   * Delete operation failed
   */
  422: unknown;
};

export type SuperAdminCompaniesControllerDeleteResponses = {
  /**
   * Company successfully deleted
   */
  200: unknown;
};

export type SuperAdminCompaniesControllerRestoreData = {
  body?: never;
  path: {
    /**
     * Company UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/companies/{uuid}/restore';
};

export type SuperAdminCompaniesControllerRestoreErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Company not found
   */
  404: unknown;
  /**
   * Restore operation failed
   */
  422: unknown;
};

export type SuperAdminCompaniesControllerRestoreResponses = {
  /**
   * Company successfully restored
   */
  200: unknown;
};

export type SuperAdminCompaniesControllerToggleStatusData = {
  body: ToggleCompanyStatusDto;
  path: {
    /**
     * Company UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/companies/{uuid}/status';
};

export type SuperAdminCompaniesControllerToggleStatusErrors = {
  /**
   * Invalid request body
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Company not found
   */
  404: unknown;
};

export type SuperAdminCompaniesControllerToggleStatusResponses = {
  /**
   * Company status updated successfully
   */
  200: unknown;
};

export type MembershipsControllerGetMyMembershipData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/memberships/me';
};

export type MembershipsControllerGetMyMembershipResponses = {
  200: unknown;
};

export type MembershipsControllerGetMembersData = {
  body?: never;
  path: {
    companyUuid: string;
  };
  query?: never;
  url: '/api/v1/memberships/company/{companyUuid}/members';
};

export type MembershipsControllerGetMembersResponses = {
  200: unknown;
};

export type MembershipsControllerRemoveMemberData = {
  body?: never;
  path: {
    membershipUuid: string;
  };
  query?: never;
  url: '/api/v1/memberships/{membershipUuid}';
};

export type MembershipsControllerRemoveMemberResponses = {
  204: void;
};

export type MembershipsControllerRemoveMemberResponse =
  MembershipsControllerRemoveMemberResponses[keyof MembershipsControllerRemoveMemberResponses];

export type MembershipsControllerUpdateMembershipData = {
  body?: never;
  path: {
    membershipUuid: string;
  };
  query?: never;
  url: '/api/v1/memberships/{membershipUuid}';
};

export type MembershipsControllerUpdateMembershipResponses = {
  200: unknown;
};

export type PlatformAuditControllerFindAllData = {
  body?: never;
  path?: never;
  query: {
    action: string;
    actorId: string;
    targetType: string;
    page: string;
    limit: string;
  };
  url: '/admin/audit-logs';
};

export type PlatformAuditControllerFindAllResponses = {
  200: unknown;
};

export type InvoicesControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number (starts from 1)
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
    /**
     * Filter by invoice status
     */
    status?:
      | 'DRAFT'
      | 'FINALIZED'
      | 'SUBMITTED'
      | 'VALIDATED'
      | 'REJECTED'
      | 'INVALID'
      | 'SENT'
      | 'OVERDUE'
      | 'COMPLETED'
      | 'VOIDED'
      | 'CANCELLED';
    /**
     * Filter invoices issued on or after this date (ISO 8601)
     */
    fromDate?: string;
    /**
     * Filter invoices issued on or before this date (ISO 8601)
     */
    toDate?: string;
    /**
     * Filter by customer UUID
     */
    customerId?: string;
    /**
     * Search invoice number (case-insensitive partial match)
     */
    invoiceNo?: string;
    /**
     * Minimum total amount (inclusive)
     */
    minAmount?: number;
    /**
     * Maximum total amount (inclusive)
     */
    maxAmount?: number;
  };
  url: '/api/v1/invoices';
};

export type InvoicesControllerFindAllErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerFindAllResponses = {
  /**
   * Invoices retrieved successfully
   */
  200: unknown;
};

export type InvoicesControllerCreateData = {
  /**
   * Invoice creation data with nested items
   */
  body: CreateInvoiceSwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/invoices';
};

export type InvoicesControllerCreateErrors = {
  /**
   * Invalid input data or product not found
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerCreateResponses = {
  /**
   * Invoice successfully created in DRAFT status
   */
  201: unknown;
};

export type InvoicesControllerExportInvoicesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
    /**
     * Filter by invoice status
     */
    status?:
      | 'DRAFT'
      | 'FINALIZED'
      | 'SUBMITTED'
      | 'VALIDATED'
      | 'REJECTED'
      | 'INVALID'
      | 'SENT'
      | 'OVERDUE'
      | 'COMPLETED'
      | 'VOIDED'
      | 'CANCELLED';
    /**
     * Filter invoices issued on or after this date (ISO 8601)
     */
    fromDate?: string;
    /**
     * Filter invoices issued on or before this date (ISO 8601)
     */
    toDate?: string;
    /**
     * Filter by customer UUID
     */
    customerId?: string;
    /**
     * Search invoice number (case-insensitive partial match)
     */
    invoiceNo?: string;
    /**
     * Minimum total amount (inclusive)
     */
    minAmount?: number;
    /**
     * Maximum total amount (inclusive)
     */
    maxAmount?: number;
    /**
     * Export file format
     */
    format: 'csv' | 'xlsx';
  };
  url: '/api/v1/invoices/export';
};

export type InvoicesControllerExportInvoicesErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Too many rows — reduce date range or add filters
   */
  422: unknown;
};

export type InvoicesControllerExportInvoicesResponses = {
  /**
   * Returns downloadable file
   */
  200: unknown;
};

export type InvoicesControllerBulkFinalizeData = {
  /**
   * Array of invoice UUIDs to finalize
   */
  body: BulkFinalizeInvoicesDto;
  path?: never;
  query?: never;
  url: '/api/v1/invoices/bulk/finalize';
};

export type InvoicesControllerBulkFinalizeErrors = {
  /**
   * Invalid input (e.g., empty array, invalid UUIDs)
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerBulkFinalizeResponses = {
  /**
   * Bulk finalize completed with detailed results
   */
  200: BulkOperationResult;
};

export type InvoicesControllerBulkFinalizeResponse =
  InvoicesControllerBulkFinalizeResponses[keyof InvoicesControllerBulkFinalizeResponses];

export type InvoicesControllerBulkSendData = {
  body: BulkSendInvoicesDto;
  path?: never;
  query?: never;
  url: '/api/v1/invoices/bulk/send';
};

export type InvoicesControllerBulkSendErrors = {
  /**
   * Invalid input (e.g., empty array, invalid UUIDs)
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerBulkSendResponses = {
  /**
   * Bulk send completed with detailed results
   */
  200: BulkOperationResult;
};

export type InvoicesControllerBulkSendResponse =
  InvoicesControllerBulkSendResponses[keyof InvoicesControllerBulkSendResponses];

export type InvoicesControllerRemoveData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}';
};

export type InvoicesControllerRemoveErrors = {
  /**
   * Cannot delete non-DRAFT invoice
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerRemoveResponses = {
  /**
   * Invoice deleted successfully
   */
  200: unknown;
};

export type InvoicesControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}';
};

export type InvoicesControllerFindOneErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Invoice not found
   */
  404: unknown;
};

export type InvoicesControllerFindOneResponses = {
  /**
   * Invoice found
   */
  200: unknown;
};

export type InvoicesControllerUpdateData = {
  body: UpdateInvoiceDto;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}';
};

export type InvoicesControllerUpdateErrors = {
  /**
   * Cannot update finalized invoice
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerUpdateResponses = {
  /**
   * Invoice updated successfully
   */
  200: unknown;
};

export type InvoicesControllerFinalizeData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/finalize';
};

export type InvoicesControllerFinalizeErrors = {
  /**
   * Cannot finalize non-DRAFT invoice
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerFinalizeResponses = {
  /**
   * Invoice finalized successfully
   */
  200: unknown;
};

export type InvoicesControllerDownloadDemoPdfData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/pdf/demo';
};

export type InvoicesControllerDownloadDemoPdfErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Invoice not found
   */
  404: unknown;
};

export type InvoicesControllerDownloadDemoPdfResponses = {
  /**
   * Invoice PDF generated and downloaded successfully
   */
  200: unknown;
};

export type InvoicesControllerSendData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/send';
};

export type InvoicesControllerSendErrors = {
  /**
   * Invoice not ready to send
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerSendResponses = {
  /**
   * Invoice queued for sending
   */
  200: unknown;
};

export type InvoicesControllerResendEmailData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/resend-email';
};

export type InvoicesControllerResendEmailErrors = {
  /**
   * Invoice not in FINALIZED or SENT status, or missing PDF URL
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerResendEmailResponses = {
  /**
   * Invoice email resent successfully
   */
  200: unknown;
};

export type InvoicesControllerSubmitEinvoiceData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/submit-einvoice';
};

export type InvoicesControllerSubmitEinvoiceErrors = {
  /**
   * Invoice not in FINALIZED status, missing LHDN credentials, or signing failed
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Invoice not found
   */
  404: unknown;
};

export type InvoicesControllerSubmitEinvoiceResponses = {
  /**
   * Invoice signed, submitted, and status transitioned to SUBMITTED
   */
  200: unknown;
};

export type InvoicesControllerVoidData = {
  body: {
    /**
     * Reason for voiding
     */
    reason: string;
  };
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/void';
};

export type InvoicesControllerVoidErrors = {
  /**
   * Cannot void DRAFT or already voided invoice
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerVoidResponses = {
  /**
   * Invoice voided successfully
   */
  200: unknown;
};

export type InvoicesControllerCancelLhdnData = {
  body: {
    /**
     * Reason for cancellation
     */
    reason: string;
    /**
     * Role of the requestor
     */
    requestorRole: string;
  };
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/cancel-lhdn';
};

export type InvoicesControllerCancelLhdnErrors = {
  /**
   * Invoice is not in SUBMITTED or VALIDATED status
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerCancelLhdnResponses = {
  /**
   * LHDN document cancellation requested
   */
  200: unknown;
};

export type InvoicesControllerGetAuditTrailData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: {
    /**
     * Page number (starts from 1)
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
  };
  url: '/api/v1/invoices/{uuid}/audit-trail';
};

export type InvoicesControllerGetAuditTrailErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Invoice not found
   */
  404: unknown;
};

export type InvoicesControllerGetAuditTrailResponses = {
  /**
   * Audit trail retrieved successfully
   */
  200: unknown;
};

export type InvoicesControllerCloneInvoiceData = {
  body?: never;
  path: {
    /**
     * Invoice UUID to clone
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/clone';
};

export type InvoicesControllerCloneInvoiceErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerCloneInvoiceResponses = {
  /**
   * Cloned invoice
   */
  201: unknown;
};

export type InvoicesControllerGetAllowedTransitionsData = {
  body?: never;
  path: {
    /**
     * Invoice UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/allowed-transitions';
};

export type InvoicesControllerGetAllowedTransitionsErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type InvoicesControllerGetAllowedTransitionsResponses = {
  /**
   * Returns array of allowed next statuses
   */
  200: unknown;
};

export type CustomersControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number (starts from 1)
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
  };
  url: '/api/v1/customers';
};

export type CustomersControllerFindAllErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type CustomersControllerFindAllResponses = {
  /**
   * Customers retrieved successfully
   */
  200: unknown;
};

export type CustomersControllerCreateData = {
  /**
   * Customer creation data
   */
  body: CreateCustomerSwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/customers';
};

export type CustomersControllerCreateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Email already exists
   */
  422: unknown;
};

export type CustomersControllerCreateResponses = {
  /**
   * Customer successfully created
   */
  201: unknown;
};

export type CustomersControllerBulkUploadData = {
  /**
   * CSV file upload
   */
  body: BulkUploadDto;
  path?: never;
  query?: never;
  url: '/api/v1/customers/bulk-upload';
};

export type CustomersControllerBulkUploadErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type CustomersControllerBulkUploadResponses = {
  201: unknown;
};

export type CustomersControllerTrackProgressData = {
  body?: never;
  path: {
    jobId: string;
  };
  query?: never;
  url: '/api/v1/customers/bulk-upload/progress/{jobId}';
};

export type CustomersControllerTrackProgressErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type CustomersControllerTrackProgressResponses = {
  200: unknown;
};

export type CustomersControllerGetUploadStatusData = {
  body?: never;
  path: {
    jobId: string;
  };
  query?: never;
  url: '/api/v1/customers/bulk-upload/status/{jobId}';
};

export type CustomersControllerGetUploadStatusErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type CustomersControllerGetUploadStatusResponses = {
  200: unknown;
};

export type CustomersControllerDownloadErrorsData = {
  body?: never;
  path: {
    errorToken: string;
  };
  query?: never;
  url: '/api/v1/customers/bulk-upload/errors/{errorToken}';
};

export type CustomersControllerDownloadErrorsErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type CustomersControllerDownloadErrorsResponses = {
  200: unknown;
};

export type CustomersControllerDeleteData = {
  body?: never;
  path: {
    /**
     * Customer UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/customers/{uuid}';
};

export type CustomersControllerDeleteErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Customer not found
   */
  404: unknown;
  /**
   * Delete operation failed
   */
  422: unknown;
};

export type CustomersControllerDeleteResponses = {
  /**
   * Customer successfully deleted
   */
  200: unknown;
};

export type CustomersControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Customer UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/customers/{uuid}';
};

export type CustomersControllerFindOneErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Customer not found
   */
  404: unknown;
};

export type CustomersControllerFindOneResponses = {
  /**
   * Customer found
   */
  200: unknown;
};

export type CustomersControllerUpdateData = {
  /**
   * Customer update data (all fields optional)
   */
  body: UpdateCustomerSwaggerDto;
  path: {
    /**
     * Customer UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/customers/{uuid}';
};

export type CustomersControllerUpdateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Customer not found
   */
  404: unknown;
  /**
   * Email already in use
   */
  422: unknown;
};

export type CustomersControllerUpdateResponses = {
  /**
   * Customer successfully updated
   */
  200: unknown;
};

export type CustomersControllerRestoreData = {
  body?: never;
  path: {
    /**
     * Customer UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/customers/{uuid}/restore';
};

export type CustomersControllerRestoreErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Customer not found
   */
  404: unknown;
  /**
   * Restore operation failed
   */
  422: unknown;
};

export type CustomersControllerRestoreResponses = {
  /**
   * Customer successfully restored
   */
  200: unknown;
};

export type ProductsControllerGetClassificationCodesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/products/classification-codes';
};

export type ProductsControllerGetClassificationCodesErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type ProductsControllerGetClassificationCodesResponses = {
  /**
   * Classification codes retrieved successfully
   */
  200: unknown;
};

export type ProductsControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Search by SKU or Name
     */
    search?: string;
    /**
     * Field to sort by (e.g. createdAt, price)
     */
    sortBy?: 'createdAt' | 'name' | 'sku' | 'price';
    sortOrder?: 'ASC' | 'DESC';
  };
  url: '/api/v1/products';
};

export type ProductsControllerFindAllErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type ProductsControllerFindAllResponses = {
  /**
   * Products retrieved successfully
   */
  200: unknown;
};

export type ProductsControllerCreateData = {
  /**
   * Product creation data
   */
  body: CreateProductSwaggerDto;
  path?: never;
  query?: never;
  url: '/api/v1/products';
};

export type ProductsControllerCreateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Invalid classification code, duplicate SKU, or creation failed
   */
  422: unknown;
};

export type ProductsControllerCreateResponses = {
  /**
   * Product successfully created with auto-generated SKU
   */
  201: unknown;
};

export type ProductsControllerDeleteData = {
  body?: never;
  path: {
    /**
     * Product UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/products/{uuid}';
};

export type ProductsControllerDeleteErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Product not found in this company
   */
  404: unknown;
  /**
   * Delete operation failed
   */
  422: unknown;
};

export type ProductsControllerDeleteResponses = {
  /**
   * Product successfully deleted
   */
  200: unknown;
};

export type ProductsControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Product UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/products/{uuid}';
};

export type ProductsControllerFindOneErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Product not found in this company
   */
  404: unknown;
};

export type ProductsControllerFindOneResponses = {
  /**
   * Product found
   */
  200: unknown;
};

export type ProductsControllerUpdateData = {
  /**
   * Product update data (all fields optional)
   */
  body: UpdateProductSwaggerDto;
  path: {
    /**
     * Product UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/products/{uuid}';
};

export type ProductsControllerUpdateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Product not found in this company
   */
  404: unknown;
  /**
   * Invalid classification code or update failed
   */
  422: unknown;
};

export type ProductsControllerUpdateResponses = {
  /**
   * Product successfully updated
   */
  200: unknown;
};

export type ProductsControllerRestoreData = {
  body?: never;
  path: {
    /**
     * Product UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/products/{uuid}/restore';
};

export type ProductsControllerRestoreErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Product not found
   */
  404: unknown;
  /**
   * Restore operation failed
   */
  422: unknown;
};

export type ProductsControllerRestoreResponses = {
  /**
   * Product successfully restored
   */
  200: unknown;
};

export type SuperadminProductsControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Search by SKU or Name
     */
    search?: string;
    /**
     * Field to sort by (e.g. createdAt, price)
     */
    sortBy?: 'createdAt' | 'name' | 'sku' | 'price';
    sortOrder?: 'ASC' | 'DESC';
  };
  url: '/api/v1/superadmin/products';
};

export type SuperadminProductsControllerFindAllErrors = {
  /**
   * Unauthorized - Super Admin access required
   */
  401: unknown;
};

export type SuperadminProductsControllerFindAllResponses = {
  /**
   * Products retrieved successfully
   */
  200: unknown;
};

export type SuperadminProductsControllerDeleteData = {
  body?: never;
  path: {
    /**
     * Product UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/products/{uuid}';
};

export type SuperadminProductsControllerDeleteErrors = {
  /**
   * Unauthorized - Super Admin access required
   */
  401: unknown;
  /**
   * Product not found
   */
  404: unknown;
  /**
   * Delete operation failed
   */
  422: unknown;
};

export type SuperadminProductsControllerDeleteResponses = {
  /**
   * Product deleted successfully
   */
  200: unknown;
};

export type SuperadminProductsControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Product UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/products/{uuid}';
};

export type SuperadminProductsControllerFindOneErrors = {
  /**
   * Unauthorized - Super Admin access required
   */
  401: unknown;
  /**
   * Product not found
   */
  404: unknown;
};

export type SuperadminProductsControllerFindOneResponses = {
  /**
   * Product found
   */
  200: unknown;
};

export type SuperadminProductsControllerRestoreData = {
  body?: never;
  path: {
    /**
     * Product UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/products/{uuid}/restore';
};

export type SuperadminProductsControllerRestoreErrors = {
  /**
   * Unauthorized - Super Admin access required
   */
  401: unknown;
  /**
   * Product not found
   */
  404: unknown;
  /**
   * Restore operation failed
   */
  422: unknown;
};

export type SuperadminProductsControllerRestoreResponses = {
  /**
   * Product restored successfully
   */
  200: unknown;
};

export type TaxRulesControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional: Filter by tax category UUID
     */
    taxCategoryUuid?: string;
  };
  url: '/api/v1/tax-rules';
};

export type TaxRulesControllerFindAllResponses = {
  /**
   * List of tax rules
   */
  200: unknown;
};

export type TaxRulesControllerCreateData = {
  body: CreateTaxRuleDto;
  path?: never;
  query?: never;
  url: '/api/v1/tax-rules';
};

export type TaxRulesControllerCreateErrors = {
  /**
   * Overlapping tax rule exists for this company
   */
  409: unknown;
};

export type TaxRulesControllerCreateResponses = {
  /**
   * Tax rule created successfully
   */
  201: unknown;
};

export type TaxRulesControllerRemoveData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/tax-rules/{uuid}';
};

export type TaxRulesControllerRemoveErrors = {
  /**
   * Cannot delete system defaults or other companies
   */
  403: unknown;
};

export type TaxRulesControllerRemoveResponses = {
  /**
   * Tax rule deleted successfully
   */
  200: unknown;
};

export type TaxRulesControllerFindOneData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/tax-rules/{uuid}';
};

export type TaxRulesControllerFindOneErrors = {
  /**
   * Tax rule not found or access denied
   */
  404: unknown;
};

export type TaxRulesControllerFindOneResponses = {
  /**
   * Tax rule details
   */
  200: unknown;
};

export type TaxRulesControllerUpdateData = {
  body: UpdateTaxRuleDto;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/tax-rules/{uuid}';
};

export type TaxRulesControllerUpdateErrors = {
  /**
   * Cannot modify system defaults or other companies
   */
  403: unknown;
};

export type TaxRulesControllerUpdateResponses = {
  /**
   * Tax rule updated successfully
   */
  200: unknown;
};

export type TaxRulesSuperAdminControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional: Filter by company UUID
     */
    companyUuid?: string;
    /**
     * Optional: Filter by tax category UUID
     */
    taxCategoryUuid?: string;
  };
  url: '/api/v1/superadmin/tax-rules';
};

export type TaxRulesSuperAdminControllerFindAllResponses = {
  /**
   * List of tax rules
   */
  200: unknown;
};

export type TaxRulesSuperAdminControllerCreateData = {
  body: CreateTaxRuleDto;
  path?: never;
  query?: never;
  url: '/api/v1/superadmin/tax-rules';
};

export type TaxRulesSuperAdminControllerCreateErrors = {
  /**
   * Overlapping tax rule exists
   */
  409: unknown;
};

export type TaxRulesSuperAdminControllerCreateResponses = {
  /**
   * Tax rule created successfully
   */
  201: unknown;
};

export type TaxRulesSuperAdminControllerRemoveData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/tax-rules/{uuid}';
};

export type TaxRulesSuperAdminControllerRemoveResponses = {
  /**
   * Tax rule deleted successfully
   */
  200: unknown;
};

export type TaxRulesSuperAdminControllerFindOneData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/tax-rules/{uuid}';
};

export type TaxRulesSuperAdminControllerFindOneErrors = {
  /**
   * Tax rule not found
   */
  404: unknown;
};

export type TaxRulesSuperAdminControllerFindOneResponses = {
  /**
   * Tax rule details
   */
  200: unknown;
};

export type TaxRulesSuperAdminControllerUpdateData = {
  body: UpdateTaxRuleDto;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/tax-rules/{uuid}';
};

export type TaxRulesSuperAdminControllerUpdateResponses = {
  /**
   * Tax rule updated successfully
   */
  200: unknown;
};

export type LhdnCredentialsControllerGetCredentialStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn-credentials/status';
};

export type LhdnCredentialsControllerGetCredentialStatusResponses = {
  200: unknown;
};

export type LhdnCredentialsControllerDeactivateCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn-credentials';
};

export type LhdnCredentialsControllerDeactivateCredentialsResponses = {
  200: unknown;
};

export type LhdnCredentialsControllerCreateCredentialsData = {
  body: CreateLhdnCredentialDto;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn-credentials';
};

export type LhdnCredentialsControllerCreateCredentialsResponses = {
  201: unknown;
};

export type LhdnCredentialsControllerUpdateCredentialsData = {
  body: UpdateLhdnCredentialDto;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn-credentials';
};

export type LhdnCredentialsControllerUpdateCredentialsResponses = {
  200: unknown;
};

export type LhdnCredentialsControllerValidateCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn-credentials/validate';
};

export type LhdnCredentialsControllerValidateCredentialsResponses = {
  201: unknown;
};

export type LhdnCredentialsControllerGetAuditLogData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn-credentials/audit-log';
};

export type LhdnCredentialsControllerGetAuditLogResponses = {
  200: unknown;
};

export type EInvoiceSubmissionsControllerListSubmissionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/e-invoice-submissions';
};

export type EInvoiceSubmissionsControllerListSubmissionsResponses = {
  200: unknown;
};

export type EInvoiceSubmissionsControllerGetStatusData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/e-invoice-submissions/{uuid}/status';
};

export type EInvoiceSubmissionsControllerGetStatusResponses = {
  200: unknown;
};

export type EInvoiceSubmissionsControllerGetQrCodeData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/e-invoice-submissions/{uuid}/qr-code';
};

export type EInvoiceSubmissionsControllerGetQrCodeResponses = {
  200: unknown;
};

export type EInvoiceSubmissionsControllerRetryData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/e-invoice-submissions/{uuid}/retry';
};

export type EInvoiceSubmissionsControllerRetryResponses = {
  201: unknown;
};

export type LhdnWebhookControllerHandleWebhookData = {
  body?: never;
  headers: {
    'x-lhdn-signature': string;
    'x-lhdn-timestamp': string;
  };
  path?: never;
  query?: never;
  url: '/webhooks/lhdn';
};

export type LhdnWebhookControllerHandleWebhookResponses = {
  200: unknown;
};

export type LhdnWebhookControllerHealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/webhooks/lhdn/health';
};

export type LhdnWebhookControllerHealthCheckResponses = {
  200: unknown;
};

export type LhdnManagementControllerListNotificationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn/notifications';
};

export type LhdnManagementControllerListNotificationsResponses = {
  200: unknown;
};

export type LhdnManagementControllerSyncNotificationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn/notifications/sync';
};

export type LhdnManagementControllerSyncNotificationsResponses = {
  201: unknown;
};

export type LhdnManagementControllerGetDocumentTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/lhdn/document-types';
};

export type LhdnManagementControllerGetDocumentTypesResponses = {
  200: unknown;
};

export type InvoiceTemplatesControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/invoice-templates';
};

export type InvoiceTemplatesControllerFindAllResponses = {
  200: unknown;
};

export type InvoiceTemplatesControllerCreateData = {
  body: CreateInvoiceTemplateDto;
  path?: never;
  query?: never;
  url: '/api/v1/invoice-templates';
};

export type InvoiceTemplatesControllerCreateResponses = {
  201: unknown;
};

export type InvoiceTemplatesControllerRemoveData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoice-templates/{uuid}';
};

export type InvoiceTemplatesControllerRemoveResponses = {
  204: void;
};

export type InvoiceTemplatesControllerRemoveResponse =
  InvoiceTemplatesControllerRemoveResponses[keyof InvoiceTemplatesControllerRemoveResponses];

export type InvoiceTemplatesControllerFindOneData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoice-templates/{uuid}';
};

export type InvoiceTemplatesControllerFindOneResponses = {
  200: unknown;
};

export type InvoiceTemplatesControllerUpdateData = {
  body: UpdateInvoiceTemplateDto;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoice-templates/{uuid}';
};

export type InvoiceTemplatesControllerUpdateResponses = {
  200: unknown;
};

export type InvoiceTemplatesControllerSetDefaultData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoice-templates/{uuid}/set-default';
};

export type InvoiceTemplatesControllerSetDefaultResponses = {
  200: unknown;
};

export type TaxCategoriesControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/tax-categories';
};

export type TaxCategoriesControllerFindAllResponses = {
  /**
   * List of tax categories
   */
  200: unknown;
};

export type TaxCategoriesControllerCreateData = {
  body: CreateTaxCategoryDto;
  path?: never;
  query?: never;
  url: '/api/v1/tax-categories';
};

export type TaxCategoriesControllerCreateErrors = {
  /**
   * Category name already exists for this company
   */
  409: unknown;
};

export type TaxCategoriesControllerCreateResponses = {
  /**
   * Tax category created successfully
   */
  201: unknown;
};

export type TaxCategoriesControllerRemoveData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/tax-categories/{uuid}';
};

export type TaxCategoriesControllerRemoveErrors = {
  /**
   * Cannot delete system defaults or other companies
   */
  403: unknown;
};

export type TaxCategoriesControllerRemoveResponses = {
  /**
   * Tax category deleted successfully
   */
  200: unknown;
};

export type TaxCategoriesControllerFindOneData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/tax-categories/{uuid}';
};

export type TaxCategoriesControllerFindOneErrors = {
  /**
   * Tax category not found or access denied
   */
  404: unknown;
};

export type TaxCategoriesControllerFindOneResponses = {
  /**
   * Tax category details
   */
  200: unknown;
};

export type TaxCategoriesControllerUpdateData = {
  body: UpdateTaxCategoryDto;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/tax-categories/{uuid}';
};

export type TaxCategoriesControllerUpdateErrors = {
  /**
   * Cannot modify system defaults or other companies
   */
  403: unknown;
};

export type TaxCategoriesControllerUpdateResponses = {
  /**
   * Tax category updated successfully
   */
  200: unknown;
};

export type TaxCategoriesSuperAdminControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Optional: Filter by company UUID
     */
    companyUuid?: string;
  };
  url: '/api/v1/superadmin/tax-categories';
};

export type TaxCategoriesSuperAdminControllerFindAllResponses = {
  /**
   * List of tax categories
   */
  200: unknown;
};

export type TaxCategoriesSuperAdminControllerCreateData = {
  body: CreateTaxCategoryDto;
  path?: never;
  query?: never;
  url: '/api/v1/superadmin/tax-categories';
};

export type TaxCategoriesSuperAdminControllerCreateErrors = {
  /**
   * Category name already exists
   */
  409: unknown;
};

export type TaxCategoriesSuperAdminControllerCreateResponses = {
  /**
   * Tax category created successfully
   */
  201: unknown;
};

export type TaxCategoriesSuperAdminControllerRemoveData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/tax-categories/{uuid}';
};

export type TaxCategoriesSuperAdminControllerRemoveResponses = {
  /**
   * Tax category deleted successfully
   */
  200: unknown;
};

export type TaxCategoriesSuperAdminControllerFindOneData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/tax-categories/{uuid}';
};

export type TaxCategoriesSuperAdminControllerFindOneErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Tax category not found
   */
  404: unknown;
};

export type TaxCategoriesSuperAdminControllerFindOneResponses = {
  /**
   * Tax category details
   */
  200: unknown;
};

export type TaxCategoriesSuperAdminControllerUpdateData = {
  body: UpdateTaxCategoryDto;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/tax-categories/{uuid}';
};

export type TaxCategoriesSuperAdminControllerUpdateResponses = {
  /**
   * Tax category updated successfully
   */
  200: unknown;
};

export type HealthControllerCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthControllerCheckErrors = {
  /**
   * The Health Check is not successful
   */
  503: {
    status?: string;
    info?: {
      [key: string]: {
        status: string;
        [key: string]: unknown;
      };
    } | null;
    error?: {
      [key: string]: {
        status: string;
        [key: string]: unknown;
      };
    } | null;
    details?: {
      [key: string]: {
        status: string;
        [key: string]: unknown;
      };
    };
  };
};

export type HealthControllerCheckError =
  HealthControllerCheckErrors[keyof HealthControllerCheckErrors];

export type HealthControllerCheckResponses = {
  /**
   * The Health Check is successful
   */
  200: {
    status?: string;
    info?: {
      [key: string]: {
        status: string;
        [key: string]: unknown;
      };
    } | null;
    error?: {
      [key: string]: {
        status: string;
        [key: string]: unknown;
      };
    } | null;
    details?: {
      [key: string]: {
        status: string;
        [key: string]: unknown;
      };
    };
  };
};

export type HealthControllerCheckResponse =
  HealthControllerCheckResponses[keyof HealthControllerCheckResponses];

export type PaymentsControllerGetPaymentsData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/payments';
};

export type PaymentsControllerGetPaymentsResponses = {
  /**
   * Payments retrieved
   */
  200: unknown;
};

export type PaymentsControllerRecordPaymentData = {
  body: CreatePaymentDto;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/payments';
};

export type PaymentsControllerRecordPaymentResponses = {
  /**
   * Payment recorded
   */
  201: unknown;
};

export type PaymentsControllerGetBalanceData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{uuid}/payments/balance';
};

export type PaymentsControllerGetBalanceResponses = {
  /**
   * Balance retrieved
   */
  200: unknown;
};

export type PaymentsControllerDeletePaymentData = {
  body?: never;
  path: {
    invoiceUuid: string;
    paymentUuid: string;
  };
  query?: never;
  url: '/api/v1/invoices/{invoiceUuid}/payments/{paymentUuid}';
};

export type PaymentsControllerDeletePaymentResponses = {
  204: void;
};

export type PaymentsControllerDeletePaymentResponse =
  PaymentsControllerDeletePaymentResponses[keyof PaymentsControllerDeletePaymentResponses];

export type ApprovalsControllerRequestApprovalData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/approvals/invoices/{uuid}/request';
};

export type ApprovalsControllerRequestApprovalResponses = {
  /**
   * Approval request created
   */
  201: unknown;
};

export type ApprovalsControllerReviewApprovalData = {
  body: ReviewApprovalDto;
  path: {
    approvalUuid: string;
  };
  query?: never;
  url: '/api/v1/approvals/{approvalUuid}/review';
};

export type ApprovalsControllerReviewApprovalResponses = {
  /**
   * Approval reviewed
   */
  200: unknown;
};

export type ApprovalsControllerGetByInvoiceData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/approvals/invoices/{uuid}';
};

export type ApprovalsControllerGetByInvoiceResponses = {
  /**
   * Approvals retrieved
   */
  200: unknown;
};

export type ApprovalsControllerGetPendingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/approvals/pending';
};

export type ApprovalsControllerGetPendingResponses = {
  /**
   * Pending approvals retrieved
   */
  200: unknown;
};

export type AnalyticsControllerGetDashboardData = {
  body?: never;
  path?: never;
  query?: {
    from?: string;
    to?: string;
  };
  url: '/api/v1/analytics/dashboard';
};

export type AnalyticsControllerGetDashboardResponses = {
  200: unknown;
};

export type AnalyticsControllerGetMonthlyRevenueData = {
  body?: never;
  path?: never;
  query?: {
    year?: number;
  };
  url: '/api/v1/analytics/revenue/monthly';
};

export type AnalyticsControllerGetMonthlyRevenueResponses = {
  200: unknown;
};

export type AnalyticsControllerGetAgingReportData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/analytics/aging';
};

export type AnalyticsControllerGetAgingReportResponses = {
  200: unknown;
};

export type AnalyticsControllerGetLhdnReportData = {
  body?: never;
  path?: never;
  query?: {
    from?: string;
    to?: string;
  };
  url: '/api/v1/analytics/lhdn';
};

export type AnalyticsControllerGetLhdnReportResponses = {
  200: unknown;
};

export type SuperAdminAnalyticsControllerGetPlatformOverviewData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/superadmin/analytics/platform-overview';
};

export type SuperAdminAnalyticsControllerGetPlatformOverviewResponses = {
  200: unknown;
};

export type SuperAdminAnalyticsControllerGetPlatformRevenueData = {
  body?: never;
  path?: never;
  query?: {
    from?: string;
    to?: string;
  };
  url: '/api/v1/superadmin/analytics/revenue';
};

export type SuperAdminAnalyticsControllerGetPlatformRevenueResponses = {
  200: unknown;
};

export type SuperAdminAnalyticsControllerGetTopCompaniesData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
  };
  url: '/api/v1/superadmin/analytics/top-companies';
};

export type SuperAdminAnalyticsControllerGetTopCompaniesResponses = {
  200: unknown;
};

export type CreditMemosControllerFindByInvoiceData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/credit-memos/invoices/{uuid}';
};

export type CreditMemosControllerFindByInvoiceResponses = {
  200: unknown;
};

export type CreditMemosControllerCreateData = {
  body: CreateCreditMemoDto;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/credit-memos/invoices/{uuid}';
};

export type CreditMemosControllerCreateResponses = {
  201: unknown;
};

export type CreditMemosControllerIssueData = {
  body?: never;
  path: {
    memoUuid: string;
  };
  query?: never;
  url: '/api/v1/credit-memos/{memoUuid}/issue';
};

export type CreditMemosControllerIssueResponses = {
  200: unknown;
};

export type CreditMemosControllerVoidData = {
  body?: never;
  path: {
    memoUuid: string;
  };
  query?: never;
  url: '/api/v1/credit-memos/{memoUuid}/void';
};

export type CreditMemosControllerVoidResponses = {
  200: unknown;
};

export type QuotationsControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    status?:
      | 'DRAFT'
      | 'SENT'
      | 'ACCEPTED'
      | 'REJECTED'
      | 'EXPIRED'
      | 'CONVERTED';
  };
  url: '/api/v1/quotations';
};

export type QuotationsControllerFindAllErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerFindAllResponses = {
  /**
   * Quotations retrieved successfully
   */
  200: unknown;
};

export type QuotationsControllerCreateData = {
  body: CreateQuotationDto;
  path?: never;
  query?: never;
  url: '/api/v1/quotations';
};

export type QuotationsControllerCreateErrors = {
  /**
   * Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerCreateResponses = {
  /**
   * Quotation created successfully
   */
  201: unknown;
};

export type QuotationsControllerRemoveData = {
  body?: never;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}';
};

export type QuotationsControllerRemoveErrors = {
  /**
   * Cannot delete non-DRAFT quotation
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerRemoveResponses = {
  /**
   * Quotation deleted successfully
   */
  200: unknown;
};

export type QuotationsControllerFindOneData = {
  body?: never;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}';
};

export type QuotationsControllerFindOneErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Quotation not found
   */
  404: unknown;
};

export type QuotationsControllerFindOneResponses = {
  /**
   * Quotation retrieved successfully
   */
  200: unknown;
};

export type QuotationsControllerUpdateData = {
  body: UpdateQuotationDto;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}';
};

export type QuotationsControllerUpdateErrors = {
  /**
   * Cannot update non-DRAFT quotation
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerUpdateResponses = {
  /**
   * Quotation updated successfully
   */
  200: unknown;
};

export type QuotationsControllerSendData = {
  body?: never;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}/send';
};

export type QuotationsControllerSendErrors = {
  /**
   * Only DRAFT quotations can be sent
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerSendResponses = {
  /**
   * Quotation sent successfully
   */
  200: unknown;
};

export type QuotationsControllerReviseData = {
  body?: never;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}/revise';
};

export type QuotationsControllerReviseErrors = {
  /**
   * Only SENT quotations can be revised
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerReviseResponses = {
  /**
   * Quotation revision created successfully
   */
  201: unknown;
};

export type QuotationsControllerAcceptData = {
  body?: never;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}/accept';
};

export type QuotationsControllerAcceptErrors = {
  /**
   * Only SENT quotations can be accepted
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerAcceptResponses = {
  /**
   * Quotation accepted successfully
   */
  200: unknown;
};

export type QuotationsControllerRejectData = {
  body?: never;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}/reject';
};

export type QuotationsControllerRejectErrors = {
  /**
   * Only SENT quotations can be rejected
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerRejectResponses = {
  /**
   * Quotation rejected successfully
   */
  200: unknown;
};

export type QuotationsControllerConvertToInvoiceData = {
  body?: never;
  path: {
    /**
     * Quotation UUID
     */
    uuid: string;
  };
  query?: never;
  url: '/api/v1/quotations/{uuid}/convert-to-invoice';
};

export type QuotationsControllerConvertToInvoiceErrors = {
  /**
   * Only ACCEPTED or SENT quotations can be converted
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type QuotationsControllerConvertToInvoiceResponses = {
  /**
   * Invoice created from quotation successfully
   */
  201: unknown;
};

export type RecurringInvoicesControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/recurring-invoices';
};

export type RecurringInvoicesControllerFindAllErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type RecurringInvoicesControllerFindAllResponses = {
  /**
   * List of recurring invoice plans
   */
  200: unknown;
};

export type RecurringInvoicesControllerCreateData = {
  body: CreateRecurringInvoiceDto;
  path?: never;
  query?: never;
  url: '/api/v1/recurring-invoices';
};

export type RecurringInvoicesControllerCreateErrors = {
  /**
   * Validation error
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type RecurringInvoicesControllerCreateResponses = {
  /**
   * Recurring invoice plan created
   */
  201: unknown;
};

export type RecurringInvoicesControllerRemoveData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/recurring-invoices/{uuid}';
};

export type RecurringInvoicesControllerRemoveErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type RecurringInvoicesControllerRemoveResponses = {
  /**
   * Plan deleted
   */
  200: unknown;
};

export type RecurringInvoicesControllerFindOneData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/recurring-invoices/{uuid}';
};

export type RecurringInvoicesControllerFindOneErrors = {
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
  /**
   * Plan not found
   */
  404: unknown;
};

export type RecurringInvoicesControllerFindOneResponses = {
  /**
   * Recurring invoice plan
   */
  200: unknown;
};

export type RecurringInvoicesControllerPauseData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/recurring-invoices/{uuid}/pause';
};

export type RecurringInvoicesControllerPauseErrors = {
  /**
   * Plan is not ACTIVE
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type RecurringInvoicesControllerPauseResponses = {
  /**
   * Plan paused
   */
  200: unknown;
};

export type RecurringInvoicesControllerResumeData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/recurring-invoices/{uuid}/resume';
};

export type RecurringInvoicesControllerResumeErrors = {
  /**
   * Plan is not PAUSED
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type RecurringInvoicesControllerResumeResponses = {
  /**
   * Plan resumed
   */
  200: unknown;
};

export type RecurringInvoicesControllerCancelData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/recurring-invoices/{uuid}/cancel';
};

export type RecurringInvoicesControllerCancelErrors = {
  /**
   * Plan is already cancelled or completed
   */
  400: unknown;
  /**
   * Unauthorized - Invalid or missing JWT token
   */
  401: unknown;
};

export type RecurringInvoicesControllerCancelResponses = {
  /**
   * Plan cancelled
   */
  200: unknown;
};

export type SuperadminAuditControllerFindAllInvoiceAuditsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/superadmin/audit/invoice-audits';
};

export type SuperadminAuditControllerFindAllInvoiceAuditsResponses = {
  200: unknown;
};

export type SuperadminAuditControllerFindInvoiceAuditByUuidData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/v1/superadmin/audit/invoice-audits/{uuid}';
};

export type SuperadminAuditControllerFindInvoiceAuditByUuidResponses = {
  200: unknown;
};

export type SuperadminAuditControllerFindAllPlatformLogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/superadmin/audit/platform-logs';
};

export type SuperadminAuditControllerFindAllPlatformLogsResponses = {
  200: unknown;
};

export type SuperadminAuditControllerFindPlatformLogByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/v1/superadmin/audit/platform-logs/{id}';
};

export type SuperadminAuditControllerFindPlatformLogByIdResponses = {
  200: unknown;
};

export type SuperadminAuditControllerGetCompanyTimelineData = {
  body?: never;
  path: {
    companyId: number;
  };
  query?: never;
  url: '/api/v1/superadmin/audit/company/{companyId}/timeline';
};

export type SuperadminAuditControllerGetCompanyTimelineResponses = {
  200: unknown;
};
